### ISSUE TITLE
Cosmetic: about dialog not properly rendering ß and ä on Windows

### ISSUE THREAD

**Issue by assarbad** [CoatiSoftware/Sourcetrail#1011]
@egraether your name as well as Jakob-Haringer-Straße aren't being rendered properly on Windows. It looks like it's applying some latin codepage to underlying UTF-8 data.

![sourcetrail-about-dialog](https://user-images.githubusercontent.com/3238620/81816880-39db6280-952c-11ea-8524-67bfe6391455.png)

**Comment by mlangkabel** [comment]
I'm able to reproduce this with the current build.

**Comment by mlangkabel** [comment]
Fixed by merge of pull request #1013.
