### ISSUE TITLE
Cannot load another project while indexing

### ISSUE THREAD

**Issue by bam80** [CoatiSoftware/Sourcetrail#1020]
Is it surmountable restriction?

**Comment by mlangkabel** [comment]
The current version of Sourcetrail does not allow this. But of course with enough effort this can be impementen. However, I fear that this may be confusing for the user, especially if the indexed project has errors. When will they be shown to the user if another project is loaded? Does the Sourcetrail display then mix files of both . the open and the indexed, projects?

In my oppinion, the simplest solution would just be while your project is indexing, open another project in another instance of Sourcetrail.

**Comment by bam80** [comment]
Think it correlates with #1022

**Comment by mlangkabel** [comment]
I don't see how those two issues correlate. But anyways, I'm against having multiple project in a "kind-of-loaded" state within one instance of Sourcetrail. That will just be confusing.

**Comment by bam80** [comment]
I meant having #1022 implemented one get results almost instantly so there is no really need to switch to other project while keep indexing the current one.

**Comment by mlangkabel** [comment]
Ok. I'm very much in favor of the other suggestion that you made. And I think that having 2 projects opened within the same instance of Sourcetrail is just making everything super complicated. Not just for the project maintainers but also for the users. Moreover they can already have 2 projects opened in 2 different instances of Sourcetrail.

**Comment by bam80** [comment]
Maybe you are right. Just a note QtCreator accepts any number of opened projects simultaneously.
