### ISSUE TITLE
function pointer indexing c/cxx

### ISSUE THREAD

**Issue by yunusemreayhan** [CoatiSoftware/Sourcetrail#1027]
Hi,

It is not indexing calls by function pointer,
for example Google test commands such ASSERT(CUSTOM_FUNCTION(x,y,z))
will not be recognized...

Thanks..

**Comment by egraether** [comment]
Yes, this is a static analysis problem. Static analysis cannot know upfront, which function will be called by a function pointer.

Can you provide a complete minimal sample please, just to make sure we talk about the same thing?

**Comment by yunusemreayhan** [comment]
Can not reproduce it, I guess, did not gave all of the includes at that time.
Case was calling functions by EXPECT_CALL.
Thanks..
