### ISSUE TITLE
Could NOT find Boost

### ISSUE THREAD

**Issue by Zhukovdpua** [CoatiSoftware/Sourcetrail#1032]
I have ubuntu 20.04, boost_1_73_0, cmake 3.16.3

I am building from source, as it was said in readme.md:
`cmake ... -DBOOST_ROOT=/home/ibse/dev_tools/boost_1_73_0 ...`

And have got: 
`CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: system program_options filesystem date_time)
  (found suitable version "1.73.0", minimum required is "1.67")`

I also tried to add `-DBOOST_LIBRARYDIR=/home/ibse/dev_tools/boost_1_73_0` as they say [here](https://stackoverflow.com/questions/57870032/cmake-v3-15-3-cannot-find-boost-v1-71-0) but it doesn't help

Full input and output: 
<details>
cmake -DCMAKE_BUILD_TYPE="Release" -DBOOST_ROOT=/home/ibse/dev_tools/boost_1_73_0 -DQt5_DIR=/home/ibse/dev_tools/Qt5.14.2/5.14.2/gcc_64/lib/cmake/Qt5 ../..

-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Version: 2020.2.27
-- setting up the buildtype for versioning
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- 'Treat warnings as errors' policy is disabled
CMake Warning at /usr/share/cmake-3.16/Modules/FindBoost.cmake:1161 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:1283 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:1921 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:168 (find_package)

CMake Warning at /usr/share/cmake-3.16/Modules/FindBoost.cmake:1161 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:1283 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:1921 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:168 (find_package)

CMake Warning at /usr/share/cmake-3.16/Modules/FindBoost.cmake:1161 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:1283 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:1921 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:168 (find_package)

CMake Warning at /usr/share/cmake-3.16/Modules/FindBoost.cmake:1161 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:1283 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:1921 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:168 (find_package)

CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: system program_options filesystem date_time)
  (found suitable version "1.73.0", minimum required is "1.67")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:2179 (find_package_handle_standard_args)
  CMakeLists.txt:168 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/ibse/tmp/Sourcetrail/build/Release/CMakeFiles/CMakeOutput.log".
</details>

**Comment by egraether** [comment]
Did you build the necessary Boost libraries, as described in the [README](https://github.com/CoatiSoftware/Sourcetrail#required-dependencies)?

**Comment by snikulov** [comment]
@Zhukovdpua you should install boost static package on Ubuntu. Or add `-DBoost_USE_STATIC_LIBS=OFF` to your CMake invocation.

**Comment by mlangkabel** [comment]
This issue seems to be inactive, as there has been no reply in a long time. Closing now.
