### ISSUE TITLE
Sourcetrail crashes while indexing SymPy in-depth

### ISSUE THREAD

**Issue by RedKnite5** [CoatiSoftware/Sourcetrail#1043]
After about 2 hours, and at least a thousand files (out of more than 3 thousand) Sourcetrail crashes (just closes) while indexing SymPy. Time to crash is variable but around 2 hours. Reproduced on both Linux (Fedora) and Windows 10, both with 8 indexer threads and in-depth indexing, in both verbose and non-verbose mode. 

The error it stops on is:

07:38:21 | 139777803896576 | SqliteStorage.cpp:233 executeQuery() | ERROR: 5: SQLITE_BUSY[5]: database is locked

Beginning and ending of log files attached. (Not attaching whole log files because they're hundreds of megabytes.)

[verbose 8 indexer threads deep indexing on Windows beginning & end of Sourcetrail SymPy log #2.txt](https://github.com/CoatiSoftware/Sourcetrail/files/4810794/verbose.8.indexer.threads.deep.indexing.on.Windows.beginning.end.of.Sourcetrail.SymPy.log.2.txt)
[verbose 8 indexer threads deep indexing on Fedora beginnng & end of Sourcetrail SymPy log.txt](https://github.com/CoatiSoftware/Sourcetrail/files/4810795/verbose.8.indexer.threads.deep.indexing.on.Fedora.beginnng.end.of.Sourcetrail.SymPy.log.txt)
[verbose 8 indexer threads deep indexing on Windows beginnng & end of Sourcetrail SymPy log #1.txt](https://github.com/CoatiSoftware/Sourcetrail/files/4810796/verbose.8.indexer.threads.deep.indexing.on.Windows.beginnng.end.of.Sourcetrail.SymPy.log.1.txt)

Tried running it with 1 indexer thread but it slows to a crawl. Takes a couple of days just to cancel the indexing while it finishes off a file. Maxes out both memory and swap file. No actual crash, but then we never get that far along in the process (maybe 5%). 

No crash when doing shallow indexing.

**Comment by mlangkabel** [comment]
Thanks for reaching out to us! The error `ERROR: 5: SQLITE_BUSY` occurrs when the sqlite database is accessed by more than one thread. I looked at the respective code part and found a buggy location that could very well have caused your issue. I fixed that code with merge of pull request #1049. 

We have scheduled a new software release for today that will include that fix.

**Comment by mlangkabel** [comment]
New version has been released. Please give it a try.

**Comment by RedKnite5** [comment]
That appears to have fixed it! It isn't done indexing yet, but it has gotten significantly farther than it has in the past! I'll let you know when it's finished if there aren't any problems before then.
