### ISSUE TITLE
Need steps to uninstall Sourcetrail on Linux

### ISSUE THREAD

**Issue by tommai78101** [CoatiSoftware/Sourcetrail#1047]
Using Ubuntu 18.04.4 LTS 64-bit with Linux kernel 5.3.0-61-generic.

I'm looking around on the Quick Setup Guide, and in the Installations section, but I couldn't find the instructions for uninstalling Sourcetrail. If a user is looking to reinstall Sourcetrail on an Ubuntu machine, it would be nice for the official documentation to provide some information on how to uninstall or reinstall. But, the documentation doesn't go in depth to explain how to uninstall Sourcetrail on Linux. 

Is it true that all I need to do is delete the `/opt/Sourcetrail` folder on the Ubuntu computer? Are there other folders I need to delete before committing to do a reinstallation of Sourcetrail?

I humbly request for a section on the Documentation page to provide a section on how to uninstall Sourcetrail, so it has a complete installation section and process.

Thanks.

**Comment by egraether** [comment]
The [uninstall.sh](https://github.com/CoatiSoftware/Sourcetrail/blob/master/setup/Linux/data/package/uninstall.sh) file should be located in `/opt/sourcetrail`.

Yes, it mainly just deletes `/opt/sourcetrail` and also removes some desktop integration files.

**Comment by tommai78101** [comment]
@egraether Hello, may I request for the documentation (or Quick Setup Guide) section to add this information to the page, since it wasn't that apparent in the documentation for me? Thanks for answering my question.

**Comment by tommai78101** [comment]
Awesome, thanks!
