### ISSUE TITLE
Java: When adding Gradle project I get "indexed 0 files".

### ISSUE THREAD

**Issue by tommai78101** [CoatiSoftware/Sourcetrail#1048]
Using Ubuntu 18.04.4 LTS 64-bit with Linux kernel 5.3.0-61-generic.

The steps that I am following from the Quick Setup Guide provided in the Readme.md is a bit vague for me, so this is what I did to setup the Java project. I'm also a newbie when it comes to using Sourcetrail, so there might be some things from the official guide webpage here that I may not understood fully:

https://www.sourcetrail.com/documentation/ 

The Java Gradle project I use for Sourcetrail is one of my personal project, linked here. Feel free to clone and make changes:  

https://github.com/tommai78101/PokemonWalking

Steps I did:

1. Download and installed Sourcetrail via the Installation section. I downloaded both the AppImage file, and the tar.gz file for Linux 64-bit.
2. After installation and executing Sourcetrail, the application launched and prompted me to set up a Sourcetrail Project Group.
3. I had to close this dialog first, and jumped straight into the **Edit** -> **Preferences** dialog, per the documentation.
4. I had to add my own Java 1.8 Runtime Library, per documentation's instructions, like so:

![image](https://user-images.githubusercontent.com/6444116/85959484-cae68b80-b96a-11ea-9528-b10e1469bae7.png)

5. **One issue I had is that I don't know which valid Java JRE system library do I need to provide. I'm assuming that I need to provide the `rt.jar` file and that's all I need to do, but there are so many JAR files. Not only that, but the documentation is vague on which JAR files is required or whether it's okay to not provide any JAR files, so I left it at that. If this can be clarified or there's a page I missed from the documentation, please let me know.**

3. After creating a Sourcetrail Project group, with the directory set to `/home/username/Documents/sourcetrailProjects`, it then prompted me to set up a Source Group. I added a new Java source group set to Gradle.
4. Since my Gradle project is using Java 12.0.1, I set my Java version to use Java 12.
5. I specified the `build.gradle` file in my root directory of my personal project (linked above).
6. I clicked on `Show Source Files` button.
7. I saved the Source Group. It then automatically attempted to scan and index files.
7. I get this following message:

![image](https://user-images.githubusercontent.com/6444116/85959573-46483d00-b96b-11ea-802e-8a31a5610151.png)

I wasn't sure what I'm doing wrong at this point. I also took a gander at this issue:

https://github.com/CoatiSoftware/Sourcetrail/issues/885

And it seems there might be a way to see the effective `build.gradle` output. Maybe my `build.gradle` file is incorrect?

https://github.com/tommai78101/PokemonWalking/blob/master/build.gradle

Any pointers would be wonderful.

**Comment by mlangkabel** [comment]
This is really strange. When you clicked the `Show Source Files` button, did it show the list of source files of your project?

I downloaded the project, created a Sourcetrail project, added the build.gradle file and that's it. Indexing worked for me, as you can see in the background of this image:

![image](https://user-images.githubusercontent.com/16242920/85995428-7f7dbd00-b9fe-11ea-9855-dedabd8f2014.png)

However, as you see, I have added all the .jar files in the jre lib folder to the system library path list, but this shouldn't affect the number of detected source files to index.

**Comment by tommai78101** [comment]
@mlangkabel 

> However, as you see, I have added all the .jar files in the jre lib folder to the system library path list, but this shouldn't affect the number of detected source files to index.

Wait, how many JAR files do I need to put? It feels like a time-consuming hassle to drag and drop each JAR file from the JRE system /lib/ folder. I guess it would make sense if I create a separate ticket requesting for a "directory path" to JRE system library JARs rather than individual JAR files?

Anyway, I'll see what I can do with the Gradle... and will report back if I find anything.

**Comment by mlangkabel** [comment]
Regarding the jars: you can just drag&drop them from the file explorer into that listbox

**Comment by tommai78101** [comment]
@mlangkabel Ok, because the documentation I looked at didn't explain how that can be done with the drag and drop system. Thanks for the tip, I'll report what I find after work.

**Comment by mlangkabel** [comment]
Can you please follow these steps? Maybe we see something:
* restart Sourcetrail
* make sure that logging is enabled
* load the project
* open your project settings
* click the "Show Source Files button" and wait for the result to show up
* quit Sourcetrail
* post the log file here

**Comment by tommai78101** [comment]
Hello @mlangkabel 

I noticed that a new stable release was released. So I waited until then for it to come out. I'm now on 2020.2.43, using the AppImage build.

I redid the steps I mentioned in the earlier post. I also used the drag & drop trick you told me to do.

I have been successful in obtaining the Source Files for my Gradle project on the Linux machine.

It now shows 86 files to index, upon clicking on the "Show Source Files" button, with a bunch of my Java files listed in the dialog box.

**Comment by mlangkabel** [comment]
Awesome! Thanks for letting us know. If anything else comes up, just open another issue :)

**Comment by Wowgreat** [comment]
I meet this problem today， and i use latest version

**Comment by Wowgreat** [comment]
Duplicate of #

**Comment by Wowgreat** [comment]
I want load https://github.com/ViRb3/TrustMeAlready.git
