### ISSUE TITLE
Sourcetrail.sh: $@ must be quoted to avoid word splitting withing command line arguments

### ISSUE THREAD

**Issue by Flupp** [CoatiSoftware/Sourcetrail#1057]
https://github.com/CoatiSoftware/Sourcetrail/blob/9a8fa94905f021a8d0da15c312752826873068e6/setup/Linux/data/package/Sourcetrail.sh#L22

When passing on the command line arguments for `Sourcetrail.sh` to `sourcetrail`, the `$@` must be quoted in order to prevent word splitting within the arguments. Corrected line:

```sh
exec "$SOURCETRAIL_PATH/bin/sourcetrail" "$@"
```

**Comment by egraether** [comment]
Thanks for reporting and suggesting a fix!
