### ISSUE TITLE
How to make doc site like Sourcetrail's

### ISSUE THREAD

**Issue by playgithub** [CoatiSoftware/Sourcetrail#1059]
The doc site for Sourcetrail (https://www.sourcetrail.com/documentation/) is very nice.
If it is generated automatically, could you tell me what tools are used?

Thanks

**Comment by mlangkabel** [comment]
Thanks! It is just plain HTML but we use [Tocify](http://gregfranko.com/jquery.tocify.js/) to automatically generate the Table of Contents from the headings of the different sections and subsections.
