### ISSUE TITLE
Feature Request: emacs/vim integration

### ISSUE THREAD

**Issue by quicknir** [CoatiSoftware/Sourcetrail#106]
Hello,

This issue not only represents a feature request, but also a datapoint as to why I am currently unlikely to use Coati, but how a relatively small change could completely swing it around.

The basic problem with Coati based on my understanding (apologies if I'm making a mistake), is that we have this very nice indexer that allows excellent browsing of source. This is a very nice tool, but it does not completely replace having an environment where you can both edit code and also do things like jump to definitions, find references, etc. I could see myself using Coati while I'm in pure reading mode, but when I'm actively editing code and quickly want to find all references to the symbol under the cursor, switching to Coati to me doesn't seem ideal.

So, it does not replace an IDE. However the IDE also has its own indexer. In my experience, all indexers require babysitting in C++, it's just a fact of life. When you add/remove files, when you wait for it to reindex after a big pull, etc. The idea of having two indexers to babysit does not seem exciting to me, so for now I'd rather just live with the indexer in my IDE, even if its not as good for pure browsing as Coati.

However, a feature that is not too bad to implement would completely mitigate this. Presumably Coati already has some kind of server/backend that does the indexing, which is queried by the frontend to display useful information. Providing vim/emacs integration with this backend could be very straightforward depending on how its designed. For an example of something very similar, rtags (which I use now) uses this architecture. The emacs integration side is just a matter of calling a simple command line program with various arguments and funneling the output back into emacs.

If this feature existed, then suddenly I would be back to only having one indexer again. I would get functionality in emacs that would hopefully be better than what I have (as more man hours are probably going to Coati as a paid product, then free software like rtags), and i would get the code browser. And I would gladly pay $100 for this functionality if it was done well. Win-win :-).

Sorry for such a long post, hope it's interesting.

Edit: I know there is already a vim plugin, but it seems to only do basic communication with Coati, i.e. send info about the current cursor location. Information does not seem to flow back into vim, i.e. no go to definition or auto completion or find references, etc. I strongly recommend taking a look at rtags to get a sense of where the bar would be for functionality to replace needing a second indexer, which is really the crux of my post.

**Comment by egraether** [comment]
Thank you for your feedback! You are absolutely right, maintaining two indexers is not nice and switching applications not either. We were aware of this problem from the start. We still decided to create Coati as an independent tool. That way it can be used by anyone, regardless of their platform and other tools they use. That is a big advantage.

To tackle the mentioned problem, we decided to write simple plugins for source editors that make switching between Coati and the editor easier. You can activate a symbol in Coati from your source editor and you can open your source editor at a certain location with Coati. We currently have plugins for Sublime Text, Visual Studio and VIM. No emacs yet unfortunately. I'm using the Sublime Text plugin and it's pretty useful to me.

You can read about them in our [plugins documentation](https://www.coati.io/documentation/#CODEEDITORPLUGINS)

What do you think about that solution?

**Comment by quicknir** [comment]
I think it is reasonable, and may work well for some, but probably not for me. I don't think that Coati as an independent tool is an unsound idea. The problem is that no matter how easy it is to switch between applications, some tasks will be very awkward. And some will be impossible, like auto-completion. So the question comes back to: does Coati handle my needs well enough that the IDE does not need an indexer? And the answer still seems to be no. And keeping two indexers is still painful, and kind of unnecessary. It will (IMHO) always be kind of uphill for Coati to battle in this very specialized space, when IDE's already provide decent code browsing (though not as good as Coati).

The main reason I actually suggested this is because the amount of effort, compared to the possible benefit, is very small. The hard part (it seems to me), is utilizing clang to parse the source and store it in the most compact, fastest possible representation so it can respond very quickly to a very wide range of queries. To make Coati work well, you anyway need to solve this problem. Once this is done, it may very well be no further work on the server side at all. You may just need to write a few hundred lines of elisp or vimscript.

The vim and emacs communities are IMHO hungry to get all the capabilities of an IDE inside their own worlds. YouCompleteMe has 11K github stars. rtags, irony, and emacs-ycmd have hundreds apiece. There's a very large number of people who want the features that only real indexing can provide, inside vim/emacs. A subset of those people will pay for the best possible product, IMHO. Coati is very impressive, but it's something brand new that you have to sell on people. On the other hand, make a video showing emacs and vim flawlessly navigating to symbols, auto completing, etc on a project the size of clang... Personally I think this would definitely have the potential to get big fast.

It may not be exactly your original vision that *some* of your customers pay primarily to get an excellent indexing backend and see the code browser as a bonus. But I think that making available a really top notch, professional clang-based parse database would really be huge, with applications beyond Coati and even beyond Vim/emacs. If you make the API public, people will start releasing cool stuff on their own which will enhance your product further. Python scripts that use your API to detect certain things, code metrics... the sky's the limit!

**Comment by egraether** [comment]
To understand why we build Coati, you need to read this [blog post by Peter Hallman](https://blogs.msdn.microsoft.com/peterhal/2006/01/04/what-do-programmers-really-do-anyway-aka-part-2-of-the-yardstick-saga/) first. He explains that developers spend about 70% of their time understanding source code and only the remaining 30% on writing and modifying it. I experienced this first hand while working on the Chrome team. There are great tools for writing code, but very little for understanding, although we spend more of our time on the latter. So with that in mind, I would argue that Coati saves you much more development time than your indexer for auto-completion.

Also your estimate on what took the most effort in developing Coati is a bit off. We spent more time on the user interface than on the indexer. Developing the user interface took years of user centered design. It involved several prototypes, surveys, user studies, questionnaires and interviews. Building an indexer is a comparably straight forward task. If you do some Google research you will find lots of existing indexers, I think some exhibit the capabilities you are looking for, e.g. [Google Kythe](https://github.com/google/kythe). I think that your suggestion to provide a public API to Coati's indexer is interesting, but our focus is on the code browsing user experience at the moment.

I know that vim and emacs users are hungry to get IDE capabilities and better code browsing, but that's hard to achieve within these applications. Their GUIs are text based and therefore very limited. They don't allow for creating interactive user experiences that involve visualization, like what we offer with Coati. So I think it was the best decision to develop Coati as a separate application. Users can still keep their familiar text editors and use Coati alongside, e.g. on a second screen.

**Comment by mlangkabel** [comment]
It seems you are talking past each other. I think @quicknir's point is that he wants to use his IDE. And in addition he may use Coati. But this would require him to run two indexers (that do roughly the same work) in parallel. Running an indexer on a big code base can take some time. Running two indexers at the same time doesn't improve the situation.

From my perspective integrating Coati as an indexing backend into vim and emacs requires more than just a little amount of work ;) So there is little chance that we will tackle an API for database queries in the near future. 

But as you mentioned: We are getting payed for improving Coati which includes improving Coati's indexing capabilities and performance. So an API that can be used by such editors may be worth writing in the future.

**Comment by quicknir** [comment]
Hi @mlangkabel , thanks for jumping in :-). I do not mean to talk past @egraether. I think Coati is very cool, I just don't honestly believe it can remove the necessity for tooling in the IDE, I think that is maybe the fundamental point, I don't know whether @egraether agrees. I'm happy to use Coati, but I can't give up e.g. jump to definition inside the IDE. When I am writing code it would be a ton of context switching.

I really, really think you guys should check out rtags, I think that quite a few of the views expressed might be altered slightly. In particular:

I agree that emacs/vim GUI's have limitations, but the kinds of things that I'm talking about are very easily well implemented in their text GUI's. Jump to definition, searching for a symbol, pop-open outlines of symbols in the current, rename symbol, jump to next occurrence, print symbol info, etc etc. Really the most used stuff does not require any fancy visualization; that is nice for things like call graphs/inheritance hierarchies/include graphs, which are great but I don't use them as often (but would happily use them in Coati, don't get me wrong, and pay for it as well).

@mlangkabel to be clear when I say "database", I just mean the following: when somebody clicks on a symbol in your frontend and your frontend e.g. jumps to where that symbol is defined, it must somehow know how to make that jump. So at some point, either when you click, or when the symbol is drawn in the first place, some kind of querying action must happen to figure out what to do; and you guys do the indexing beforehand and somehow store the results. So you already have a database. A CLI for that database where you feed it symbol names and it returns e.g. file and line number where defined is not that hard I think you'll agree (if you don't already have it). Aside from that, rtags has about 5K lines of elisp, and that's all. That's the integration, which is quite polished, has lots of customization variables, and spends a lot of code on things you probably wouldn't need because it would make more sense to drop back to Coati for them (for instance, drawing text based inheritance hierarchies).

Anyhow, even aside from the technical viewpoint IMHO it has much more potential to make money. I'm just one datapoint but I'd guess that very few of the C++ developers I know would be that excited to use something like Coati. I know plenty of people from whom even getting the IDE indexer is such a pain that they limp along with it half working most of the time. Trying to convince those guys to drop their IDE indexer completely, or work on maintaining two will be very hard (and to pay money for it as well).

**Comment by simonpp** [comment]
I'm also using emacs+rtags. I see Coati as a useful tool to explore and understand code. I completely agree with the statements above by quicknir. Except that I think that I can live with running two indexers for the moment, but sharing the database with rtags would be a big plus and I'd also be willing to pay more for having such features.

**Comment by egraether** [comment]
We want to offer Sourcetrail for as many developers as possible, that's why we don't integrate with certain editors. We offer editor plugins for synchronization though.
