### ISSUE TITLE
Function definitions and variable instantiations in header files are not recognized! [Explanation and temorary solution]

### ISSUE THREAD

**Issue by Skodra** [CoatiSoftware/Sourcetrail#1061]
![image](https://user-images.githubusercontent.com/11903296/87857592-39928580-c928-11ea-85aa-f62aa155b6c4.png)

CHIP_Init is defined in included file em_chip.h but can't be seen as there is macro in-front of it's definition, that's at least my thinking. As all other functions defined in the same manner (that are in files from the same directory), but that don't have that macro, are indexed. I also noticed that when there are ifdef macros for include files, Sourcetrail won't recognize them, maybe because I didn't defined them as in original IDE.

![image](https://user-images.githubusercontent.com/11903296/87857641-88401f80-c928-11ea-9f23-a750af42dedb.png)

Original IDE is Simplicity IDE, used for ARM Cortex M4.

**Comment by mlangkabel** [comment]
I don't think that the macro is the issue here. Even if neither `MSC_CACHECMD_INVCACHE` nor `MSC_CMD_INVCACHE` are defined, the function `CHIM_Init` would still have a body and thus the compiler would still see it as a definition. 

I guess that you have created the Sourcetrail project by using an "Empty Source Group"? In that case: Did you add the `em_chip.h` file or any of its parent directories to the list of "Files and Directories to index"?

**Comment by Skodra** [comment]
MSC_CACHECMD_INVCACHE doesn't make any impact, even if it's not defined. Thank you for engaging.

**But I have found the problem!**

If the header file has and kind of **instantiation** or **function definition** (i don't mean declaration), non of that would be recognized by Sourctrail. So my dirty solution is to include such header files in source file list, so that their code would be recognized. This is a really big bug I would say, if there are big projects, people can individualy be looking what header files to include like this, I it may not even solve this problem in some cases.

**Solution:**

Now the program recognizes CHIP_Init() defined in em_chip.h
![image](https://user-images.githubusercontent.com/11903296/88150577-de031900-cc01-11ea-8e17-b7715b5505d4.png)

But i had to include it in source file list, among other files... even though it's already in include directory and is being included in many source files.
![image](https://user-images.githubusercontent.com/11903296/88150691-025ef580-cc02-11ea-8d08-d3d06bf4af3d.png)

If someone is wondering, including em_chip.h explicitly in include files doesn't make any difference. I found this program to be the best, most useful and most appealing, 
I would really like continue using it and help improve it! Hope this problem can be resolved quickly as I am using it for my masters project, I would be of huge help. I am only embedded engineer, but maybe if someone instructs me I could help.

**Comment by egraether** [comment]
This is expected behavior. We don't index all header files by default, only if they, or any parent directory, is added to **Files and Directories to Index**.

Alternatively you could also add the directory `CMSIS/Include`, so you don't have to add each header file individually.

**Comment by Skodra** [comment]
I don't think that this is normal behavior. Adding whole `CMSIS/Include` will generate a lot of errors because **all** of the header files will become its translation unit. While adding individual header files as source files besides being impractical (and I would say wrong and unnecessary), is something you would never do in IDE like Eclipse as it can lead to multiple instances in different .o files, and linker having problems with duplicate instances. Of course Sourcetrail doesn't build my project so it is not concerned with that, but it should work as Eclipse or any other IDE.

What is happening is, header files are being inserted in source files in predecessor step as it should, but then any instances in that source file that are due to header inclusion are not registered.

I have found workaround this problem, but it's super impractical for bigger projects!

**Comment by egraether** [comment]
Header files do not become translation units when added to **Files and Directories to Index**.

A long time ago we had separate lists for source and header files, but many users had issues with it. So we changed to a single list, which some users also have issues with. Either way, there are users with issues.

**Comment by Skodra** [comment]
Is **Files and Directories to Index** list for files that would be processed and **Include Paths** list for files to be recognized as possible includes, but wont be processed to the fullest? **Files and Directories to Index** list is a super set of **Include Paths**? 

Do I then need to include same files (header files) both in **Include Paths** and **Files and Directories to Index**? Also that seems problematic, when header files from **Files and Directories to Index** are included in multiple translation units (source files) and also have global instantiations.
