### ISSUE TITLE
'clang-tool' in compile_commands.json, what is it?

### ISSUE THREAD

**Issue by vexe** [CoatiSoftware/Sourcetrail#1066]
Hi, this is more a question than an issue.

I mainly come across your work through searching for ways to generate compile_commands.json on Windows (for use for clangd integration in a custom text editor I'm writing) I was curious as to what the 'clang-tool' actually mean in the generated json file in the "command" field? Asked around in the LLVM community they're not familiar with that command name. I thought it was something defined in the VS dev console, but it wasn't. I looked around in your source, most the searches were just related to code gen.

Thanks for any help!
Cheers

**Comment by mlangkabel** [comment]
Hey, the [documentation](https://clang.llvm.org/docs/JSONCompilationDatabase.html) states:
>__command:__ The compile command executed. After JSON unescaping, this must be a valid command to rerun the exact compilation step for the translation unit in the environment the build system uses. Parameters use shell quoting and shell escaping of quotes, with ‘"’ and ‘\’ being the only special characters. Shell expansion is not supported.

So this will be the complete command that can be executed. For example if you want to compile the code, the command could be `clang++` with the respective command line arguments. As far as I know, for custom tools that use the Clang frontend, is it required to set the command to `clang-tool`. Some time ago, we changed Sourcetrail to replace whatever command was in the `compile_commands.json` with `clang-tool`, so we don't need to have this in the command anymore. 

What would you need the command to be?

**Comment by vexe** [comment]
Hey, thanks for the reply!

It looks like for my usage of it in clangd, it doesn't really matter what the name of the command is, it seems to mostly care about the flags that come after it to know which files to index and how to do it. I'll keep it set to clang-tool for now as it seems to be working good!

> As far as I know, for custom tools that use the Clang frontend, is it required to set the command to clang-tool

Do you remember where you read that? Clang doc somewhere?

**Comment by mlangkabel** [comment]
Sorry, I really don't remember anymore.
