### ISSUE TITLE
+1 follow an array by name pointer

### ISSUE THREAD

**Issue by mnnahvi** [CoatiSoftware/Sourcetrail#1074]
if an array used without "[ ]" it is a pointer to first array element and it seems that it is not handle by  Sourcetrail.
for example
`int foo[10];
struct strct = {
int a;
int * b;
};
struct strct = {10, foo};`

foo in strct is not traceable;

**Comment by mlangkabel** [comment]
You test code is not compiling, so I guess you mistyped it. I tested your issue with the following code:

```
int foo[10]; 
struct strct { int a; int * b; }; 
strct strctf = {10, foo};
```

This works. If I click `foo`, both occurrences of `foo` are highlighted.
