### ISSUE TITLE
Using sourcetrail as a source code analysis library?

### ISSUE THREAD

**Issue by virtuald** [CoatiSoftware/Sourcetrail#1076]
It seems like it could be really useful to build sourcetrail as a shared library and utilize it to do various types of source code analysis. Wrapping it in a Python API would be even more useful. Alternatively, running analysis plugins from the GUI instead of as a shared library could also be useful for the same types of things.

I'd love to be able to write automated scripts that do things like "find all references to the global variable 'foo' at 'bar.cpp:341'", or "give me a list of all the callers of 'Foo::bar()'"... etc etc.

How much work would be required to do such a thing? Looking through the source code it seems like it's already well-structured for this, just lacks documentation of the internal API.

**Comment by mlangkabel** [comment]
I think the easiest way to do this is call the Sourcetrail command line API to build an index of the target code base. The index is written to a `.srctrldb` file, which is basically an sqlite database file which is structured like [this](https://github.com/LouisStAmour/SourcetrailTypescriptIndexer/blob/master/docs/SourcetrailDB%20Schema.pdf). You could just use python to query the database to get the results that you need.
