### ISSUE TITLE
Error while executing maven command

### ISSUE THREAD

**Issue by ashima15448** [CoatiSoftware/Sourcetrail#1079]
I am facing the following problem when I try to create my maven project:
![image](https://user-images.githubusercontent.com/32170935/93425558-e4e39a80-f8d7-11ea-92bd-d2dfa33108a7.png)

**Comment by mlangkabel** [comment]
Sourcetrail calls maven for multiple different reasons with different commands. From that screenshot I don't see which command was failing. There should be some more info in Sourcetrail's log file. Can you take a look? Or post the log file here? Just the lines around the error would also be enough.

**Comment by mlangkabel** [comment]
No reply, closing now...
