### ISSUE TITLE
Build error: no member named 'globalPos' in 'QWheelEvent'

### ISSUE THREAD

**Issue by tiendq** [CoatiSoftware/Sourcetrail#1084]
I tried to build with following command but got a build error:

`cmake -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=/Users/tiendo/boost -DQt5_DIR=/Users/tiendo/Qt/5.15.1/clang_64/lib/cmake/Qt5` ..

Error:

```
/Users/tiendo/GitHub/Sourcetrail/src/lib_gui/qt/element/code/QtCodeArea.cpp:43:62: error: no member named 'globalPos' in
      'QWheelEvent'
                QPoint globalMousePos = dynamic_cast<QWheelEvent*>(event)->globalPos();
```

My environment:
OS: macOS 10.15.6
Clang: 1103.0.32.62 - /usr/bin/clang

**Comment by egraether** [comment]
You use the wrong Qt version. We are still on version `5.12.3`, you have `5.15.1`.

**Comment by tiendq** [comment]
Thank you, I just built it successfully with Qt `5.12.3`.
