### ISSUE TITLE
Inheritance graph doesn't show up nodes that inherit from a template specialization

### ISSUE THREAD

**Issue by luisgarcia2** [CoatiSoftware/Sourcetrail#1086]
Hi, I'm trying to understand the code from QCustomPlot, a charting library, and there are some types of charts that inherit from a template specialization (e.g. QCPCurve), and those don't show up on the inheritance graph. Maybe the problem is that the template specialization types aren't indexed?

**Comment by mlangkabel** [comment]
Hey @luisgarcia2, it should be working. For testing, can you please try to index a single .cpp file with the following contents:
```
template <typename T>
class Foo {};

class Bar: public Foo<int> {};
```
Is that working? Or are you talking about something else?

**Comment by mlangkabel** [comment]
No answer, closing now. Feel free to re-open with more info.
