### ISSUE TITLE
Moving to LLVM 11

### ISSUE THREAD

**Issue by serge-sans-paille** [CoatiSoftware/Sourcetrail#1088]
LLVM 11 is about to be released, what's the usual plan to move to latest version, if any?

**Comment by mlangkabel** [comment]
Usually we 
* make a branch
* test if it works on one platform and make the required API changes (if any) on that branch
* test if it works on linux, osx and windows
* update the linux docker image to use the new LLVM version
* update the linux CI on the branch to use the new docker image
* update the documentation on the branch 
* pull the changes to master

**Comment by serge-sans-paille** [comment]
Thanks for sharing! I bring some good news: sourcetrail package on Fedora didn't need any change to build with llvm11: https://koji.fedoraproject.org/koji/taskinfo?taskID=52952133

**Comment by mlangkabel** [comment]
Done with merge of pull request #1116.
