### ISSUE TITLE
.cm2 file can not be indexed

### ISSUE THREAD

**Issue by Raphael95** [CoatiSoftware/Sourcetrail#1101]
the .cm2 file in the compiler_commands.json  can not be indexed by Sourcetrail, so the  symbols in .cm2 file can not be resolved 。Has anybody met the same question ?

**Comment by mlangkabel** [comment]
Should the .cm2 file be treated as a source of a header file?

**Comment by Raphael95** [comment]
> Should the .cm2 file be treated as a source of a header file?

No, it should be treated as source files just like .c or .cpp

**Comment by mlangkabel** [comment]
I don't think that the clang compile recognizes .cm2 files as source files. To test this, could you temporarily rename one of your .cm2 files to .c or .cpp (depending on the contents) including the entry in the compile_commands.json and run the indexer to see if it is getting indexed?

**Comment by mlangkabel** [comment]
No reply, closing now. Feel free to re-open with more info.
