### ISSUE TITLE
Sourcterail can not index file in some cases, it my be caused by the wrong compile_commands.json file

### ISSUE THREAD

**Issue by Raphael95** [CoatiSoftware/Sourcetrail#1103]
Sourcterail can not index files in some cases, it may be caused by the wrong compile_commands.json file, but i do not know what's wrong with the cdb file, how should i locate the errors?

**Comment by mlangkabel** [comment]
How did you generate the cdb file? What are the errors that show up diring indexing?

**Comment by mlangkabel** [comment]
No response in a while. Closing now.
