### ISSUE TITLE
Sourcetrail find the wrong headers

### ISSUE THREAD

**Issue by Raphael95** [CoatiSoftware/Sourcetrail#1105]
In my project, a source file named A.c ,  two headers named B.h in different directores:  /A/include and  /B/include.  A.c include B.h that defined in /A/include, but sourcterail find another headers, it associate A.c with B.h that defined in directory: /B/include.

how should i resolve this errors ?

**Comment by mlangkabel** [comment]
Did you set up your Sourcetrail project manually or did you use a compile_commands.json file? In any case I think that switching the positions of `/A/include` and `/B/include` in your header search paths will solve the issue.
