### ISSUE TITLE
Overlapping characters

### ISSUE THREAD

**Issue by profawk** [CoatiSoftware/Sourcetrail#1106]
linux running sway wayland and xwayland
sourcetrail 2020.2.43
in the search bar characters are overlapped hiding one another
![sceenshot-2020-11-07T14:05:39+02:00](https://user-images.githubusercontent.com/18243325/98440614-64386200-2102-11eb-8d53-93d63c54d5fe.png)
this always happens.

**Comment by mlangkabel** [comment]
Hmm, this does not look like a monospace font. Can you try to select a monospace font in your Sourcetrail preferences and see if the issue is gone?

**Comment by profawk** [comment]
of course! should have thought about it!
works perfectly
thanks alot
