### ISSUE TITLE
Feature Request: Static Analysis Support

### ISSUE THREAD

**Issue by buffersandbeer** [CoatiSoftware/Sourcetrail#1108]
I spend a lot of time reviewing code statically without setting up a development environment. It would be great if you could use Sourcetrail without needing a build environment for the code. For example, you can't index Java code without JDK installed. Or on C++ projects you get constant indexing errors if you don't have the right build chain installed.

**Comment by mlangkabel** [comment]
Thanks for the feedback. Let me close this issue and link issues #1091 and #1115 here, so that we have one issue open per language. The smaller scope will make it more easy to discuss and implement.
