### ISSUE TITLE
Unable to include compiler defined files in 'Empty C++ Source Group'.

### ISSUE THREAD

**Issue by ajiten** [CoatiSoftware/Sourcetrail#1111]
Am having a two file code, attached as GraphTest.cpp, graph.hpp. But, got fatal error in the first include file for algorithm.h in the header file. I am sure would give error for other includes too, as all others are sequentially after that. I tried by taking two simplest files: code.h, sum.h. These are also attached, but the same type of error - i.e. on including system-defined header files occurs. This time the specific Fatal error is: ""iostream" file not found

**Comment by ajiten** [comment]
[code.zip](https://github.com/CoatiSoftware/Sourcetrail/files/5542336/code.zip)
[graph.zip](https://github.com/CoatiSoftware/Sourcetrail/files/5542337/graph.zip)
[GraphTest.zip](https://github.com/CoatiSoftware/Sourcetrail/files/5542338/GraphTest.zip)
[sum.zip](https://github.com/CoatiSoftware/Sourcetrail/files/5542339/sum.zip)

**Comment by ajiten** [comment]
Am running on Windows 7.

**Comment by ajiten** [comment]
> Looks like the c++ standard headers have not been found. Can you compile those files on your system?

Yes, but ran easily at onlinegdb.com by creating a new project. I  don't know how to provide locally such environment that provides the desired header object files.

**Comment by ajiten** [comment]
> Looks like the c++ standard headers have not been found. Can you compile those files on your system?

Just now ran on Dev-C++ with added compiler flag -std=c++11. Also, my system is Win7.

**Comment by mlangkabel** [comment]
Sourcetrail needs to have a functional C/C++ compiler environment set up on the system in order to index your code.
