### ISSUE TITLE
Feature request: Scheduled and Triggered refresh

### ISSUE THREAD

**Issue by nhorlock** [CoatiSoftware/Sourcetrail#1113]
Just a few thoughts that occurred to me as I sit waiting for a refresh to complete :-)

It would be useful to be able to schedule a refresh to happen overnight or at a selected time. Another option (though more invasive) is to refresh based on the number of changed files. Furthermore, being able to trigger a refresh from CI pipeline would be an interesting option.

## Time-based refresh
Allow a schedule to be defined per project. 
Ideally, this would allow scheduling like you might AV scans or meetings
* Days of the week (list of days, or every day)
* Time of day (explicit time of day HH:MM)

## Change based refresh
Automatically prompt to refresh when the number of changes goes above a user-defined threshold.
This could be percentage of files tracked or an explicit number.

## Triggered refresh
From the IDE controller and/or from a CI hook, trigger a full or partial refresh

**Comment by mlangkabel** [comment]
@nhorlock, thanks for reaching out. This should already be possible via Sourcetrail's CLI using the `index` command. This allows custom scripts or a CLI to trigger the Sourcetrail indexing.
