### ISSUE TITLE
Strange pink GUI and illegal version 0.0.0 when running Sourcetrail 2020.2.43-3.fc33 on Fedora 33 

### ISSUE THREAD

**Issue by mrolappe** [CoatiSoftware/Sourcetrail#1123]
As the title already says the GUI looks pink and displays an illegal version when running said version on Fedora 33 installed via dnf. Please see the screenshot.

The problem does not show when running the same version downloaded from GitHub, neither the AppImage nor the tgz variant.

![pink! it's my new obsession](https://user-images.githubusercontent.com/215132/103353251-ab125a80-4aa8-11eb-88ee-143ae4674566.png)

**Comment by mlangkabel** [comment]
It looks like Sourcetrail is unable to find the stylesheets for the UI. Usually this happens if the working directory is wrong. I'm not quite sure about Fedora, but I think the working dir should contain the `data` and the `user` folder like [this](https://github.com/CoatiSoftware/Sourcetrail/tree/master/bin/app).

**Comment by mrolappe** [comment]
What exactly does working directory mean in this context?

I do not see any `data` or `user` directory in the package. 

> ✘ mrolappe@fedora-dt-jmj  ~  rpm -qil sourcetrail
> Name        : sourcetrail
> Version     : 2020.2.43
> Release     : 3.fc33
> Architecture: x86_64
> Install Date: Do 31 Dez 2020 15:51:00 CET
> Group       : Unspecified
> Size        : 9481258
> License     : GPLv3
> Signature   : RSA/SHA256, Mi 29 Jul 2020 18:27:24 CEST, Key ID 49fd77499570ff31
> Source RPM  : sourcetrail-2020.2.43-3.fc33.src.rpm
> Build Date  : Mi 29 Jul 2020 16:00:27 CEST
> Build Host  : buildhw-x86-04.iad2.fedoraproject.org
> Packager    : Fedora Project
> Vendor      : Fedora Project
> URL         : https://www.sourcetrail.com/
> Bug URL     : https://bugz.fedoraproject.org/sourcetrail
> Summary     : a free and open-source interactive source explorer
> Description :
> 
> Sourcetrail is a free and open-source cross-platform source explorer that helps
> you get productive on unfamiliar source code.
> /usr/bin/sourcetrail
> /usr/bin/sourcetrail_indexer
> /usr/lib/.build-id
> /usr/lib/.build-id/36
> /usr/lib/.build-id/36/088d423f22b7f7ad0e2933eecbea9388a7d277
> /usr/lib/.build-id/9e
> /usr/lib/.build-id/9e/47eda5189f0c6d9dc8c0f4699cb263b7b70029
> /usr/share/applications/sourcetrail.desktop
> /usr/share/icons/hicolor/128x128/apps/sourcetrail.png
> /usr/share/icons/hicolor/256x256/apps/sourcetrail.png
> /usr/share/icons/hicolor/48x48/apps/sourcetrail.png
> /usr/share/icons/hicolor/512x512/apps/sourcetrail.png
> /usr/share/icons/hicolor/64x64/apps/sourcetrail.png
> /usr/share/licenses/sourcetrail
> /usr/share/licenses/sourcetrail/LICENSE.txt
> /usr/share/mime/packages/sourcetrail-mime.xml
>

**Comment by mlangkabel** [comment]
By "working directory" I mean the directory from where you start Sourcetrail. But it looks like our package does not include the required data. Where did you get that package? How was it built?

**Comment by mrolappe** [comment]
I simply installed the package via dnf. No clue how it was built. But if I understand you correctly there are files missing from the package which cause the problem.

>  ✘ mrolappe@fedora-dt-jmj  ~  dnf info sourcetrail
> Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:10 am Do 25 Feb 2021 08:36:11 CET.
> Installierte Pakete
> Name         : sourcetrail
> Version      : 2020.2.43
> Release      : 3.fc33
> Architecture : x86_64
> Size         : 9.0 M
> Quelle       : sourcetrail-2020.2.43-3.fc33.src.rpm
> Repository   : @System
> Aus Paketque : fedora
> Summary      : a free and open-source interactive source explorer
> URL          : https://www.sourcetrail.com/
> Lizenz       : GPLv3
> Description  :
>              : Sourcetrail is a free and open-source cross-platform source explorer that helps
>              : you get productive on unfamiliar source code.
>

**Comment by mlangkabel** [comment]
Yes, it looks like there are files missing. And usually the version number is compiled into the executable. So it looks like the setup that was building the package had some issues.

**Comment by matejak** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1971515

**Comment by matejak** [comment]
Is there any documentation for package maintainers? The released tarball contains a README that explains how to install the package to a given directory, but maintainers usually like to put binaries and application data where other packages in the particular distribution do so, e.g. binaries to `/usr/bin`, and data to `/usr/share/sourcetrail` and so on.
Does the package allow something like that?

**Comment by matejak** [comment]
Anyway, this has been fixed - see the referenced BZ, so this issue can be closed.

**Comment by mlangkabel** [comment]
Thanks for the notification!
