### ISSUE TITLE
No Mac or Windows builds for Release 2021.1

### ISSUE THREAD

**Issue by ajdavis** [CoatiSoftware/Sourcetrail#1128]
Hello! I notice that past releases included Mac and Windows builds, but Release 2021.1 includes only Linux builds:

https://github.com/CoatiSoftware/Sourcetrail/releases/tag/2021.1

Thanks!

**Comment by mlangkabel** [comment]
Thanks for the notification! 2021.1 should only be a tag to indicate that development for the new release has started. Somehow our linux CI managed to ignore that it should not build release packages for _annotated_ tags and went full speed ahead ;)
So the build contains the same features as the 2020.4 release.

I will delete the release (but keep the tag) now. Once 2021.1 will actually be released it will be tagged `2021.1.XX`
