### ISSUE TITLE
Making a one-time donation

### ISSUE THREAD

**Issue by Gansgar** [CoatiSoftware/Sourcetrail#1130]
Hey there,
would it be possible to give you a one-time donation instead of a monthly subscription? It's too easy for me to forget the latter ones.

- George

**Comment by mlangkabel** [comment]
Hm, it looks like this is not possible via Patreon. 
You could either "Make a custom pledge" and cancel it as soon as you get the mail from Patreon that lists your pledges at the start of the next month or, if you are really worried that you forget it, you could make a very small pledge that wouldn't hurt if you forget to cancel it for a few months ;)
