### ISSUE TITLE
Detect cyclic dependency ?

### ISSUE THREAD

**Issue by prunier** [CoatiSoftware/Sourcetrail#1132]
Hello,
thank you for your tool. 

I'am looking for cyclic dependecies in a C++ code.

I've used 3 files: a.h, b.h and main.cpp as mentioned in https://en.wikipedia.org/wiki/Circular_dependency.

And we can assess that A uses B and B uses A into two separated graph (one example below) 
but... it seems difficult (impossible ?) to get a view showing  both the cyclic links between the classes A and B.

Am'I wrong ?
Cheers, Dominique 

![image](https://user-images.githubusercontent.com/5794315/105984484-7939e700-609a-11eb-924e-7fa434e4f6a3.png)

**Comment by mlangkabel** [comment]
If there are multiple edges between 2 classes, Sourcetrail may bundle those edges (orange edge in the image):
![image](https://user-images.githubusercontent.com/16242920/106046613-c80b6f00-60e2-11eb-8f34-5c71a3e47668.png)
If you click such a bundled edge, it expands and shows all the bundled edges:
![image](https://user-images.githubusercontent.com/16242920/106046661-d8bbe500-60e2-11eb-9da5-7b69a85173cd.png)
