### ISSUE TITLE
Filelist shows 0 files when using gradle to add java project files

### ISSUE THREAD

**Issue by riteshudhani** [CoatiSoftware/Sourcetrail#1133]
Hi, I am trying to load an Android project in Sourcetrail but Filelist shows 0 files when using gradle to add Java files. 

After I create a new project, I try to add a new source group for Java using "Java source group from Gradle". I select the root build.gradle file and click on show source files. Here it lists 0 files in the FileList popup window, even though there are multiple projects in the same root folder of the project containing the root gradle file. Is there any issue or am I missing something? Please confirm.

**Comment by mlangkabel** [comment]
I'm sorry, currently Sourcetrai's Gradle setup just supports Gradle build configs that are based on the "java" plugin. Issue #502 is a request for  supporting Android projects.
