### ISSUE TITLE
Any paid alternatives

### ISSUE THREAD

**Issue by alyfreym** [CoatiSoftware/Sourcetrail#1148]
Does anyone know any paid alternatives?

**Comment by alexfromcaartaa** [comment]
Below I listed some of the alternatives to Sourcetrail that have paid versions (not exactly the same but similar). 
btw, I'm super passionate about helping developers to navigate and understand code quickly and seamlessly and currently teaming up with some of the best industry experts to continue the mission of Sourcetrail. If anybody is interested to learn more about what we (a team of Ex Facebook/Google/Okta) are up to, or you are kind enough to brainstorm with us, share your thoughts and experience, or collaborate with us please hit me up in [linkedin](https://www.linkedin.com/in/alexbit/)! Thank you!

1. [codemap.app](https://codemap.app/)
2. [Softagram](https://softagram.com/desktop/)
3. [Flow](http://app.findtheflow.io/recording.html?url=aHR0cDovL2Zsb3ctZGVtby5ldS1jZW50cmFsLTEuZWxhc3RpY2JlYW5zdGFsay5jb20vcmVjb3JkaW5ncy9zcHJpbmctcGV0Y2xpbmlj)
4. [CodeLogic](https://codelogic.com/)
5. [Sonargraph](https://www.hello2morrow.com/products/sonargraph/explorer)
6. [NDepend](https://www.ndepend.com/docs/visual-studio-dependency-graph), also see CPPDepend, JArchitect
7. [Structurizer](https://structurizr.com/help/tour)
8. [structure101](https://structure101.com/products/workspace/)
9. [Metabob](https://metabob.com/#visual-map)
10. [Code Iris](https://plugins.jetbrains.com/plugin/7324-code-iris)
11. [CodeMR](https://plugins.jetbrains.com/plugin/10811-codemr)
