### ISSUE TITLE
Problem with long paths running on windows

### ISSUE THREAD

**Issue by mrkdev** [CoatiSoftware/Sourcetrail#1149]
Sourcetrail fails in the phase of 'Preparing for Indexing' if it encounters long filepaths on windows.
It then stays in that phase for ever and never starts indexing.

Error: TaskRunner.cpp:45 TaskRunner::update() | ERROR: boost::filesystem::canonical: No such file or directory: "[long path]"

Support for long filenames/long paths is enabled on windows and other tools like git can handle that easily.
Sourcetrail should at least skip those paths instead of stopping and freezing the 'preparing' dialog.

Sourcetrail 2020.4.35
Windows 10
Java 1.8.0 64-Bit
Path+Filename length: 261 chars

**Comment by mlangkabel** [comment]
This is interesting. On my Windows 10 system I get the same error message, but instead of freezing it crashes. Thanks @mrkdev for pointing this out!

**Comment by mlangkabel** [comment]
Fixed by merge of pull request #1151. Now those paths should be ignored.
