### ISSUE TITLE
Sourcetrail shows only file names instead of symbols

### ISSUE THREAD

**Issue by vborovikov** [CoatiSoftware/Sourcetrail#1158]
I built Sourcetrail from source with Java support and loaded the provided javaparser project. It shows me a list of files and is able to search the file names but not symbols from the code. And Sourcetrail doesn't show any relationship graphs like in the guidelines.

This is how it looks for any java project.

![image](https://user-images.githubusercontent.com/6218979/110199273-8015ff80-7e79-11eb-9b7b-656f3f8dd6b5.png)

**Comment by mlangkabel** [comment]
Looks like your build fails to call the Java code. The File nodes are still recorded by our C++ code, and then the Java indexer, which is written in Java, is called via JVM, which is somehow not working for you. Do you see any strange messages in your log or console while you start indexing a Java project?

**Comment by vborovikov** [comment]
I see these messages in the log file:

05:02:50 | 11544 | JavaEnvironment.cpp:173 JavaEnvironment::getJavaClass() | ERROR: class com/sourcetrail/JavaIndexer not found in JVM environment

**Comment by mlangkabel** [comment]
Hm, looks like the Java indexer JAR has not been loaded. Do your tests run without errors?

**Comment by vborovikov** [comment]
After that I've installed regular Java 8 from Oracle. It didn't work with my build either so I've installed the latest Sourcetrail beta.

Now with the beta it all works as expected.

For my build I used -DBUILD_JAVA_LANGUAGE_PACKAGE=ON flag in addition to the basic Build on Windows instructions. Maybe there are other flags that are needed for the Java support...

**Comment by mlangkabel** [comment]
Thanks for the update!
