### ISSUE TITLE
Latest SourceTrail still fails working with ANY JRE/JDK version (reopening #955)

### ISSUE THREAD

**Issue by Hamid-K** [CoatiSoftware/Sourcetrail#1161]
This issue was previously discussed as #955 but despite many feedback from users it was closed. The latest version is still facing with the same issue. 

I spend a couple of frustrating hours today, trying every trick in the book, with no luck on the latest MacOS version and various Java versions. The only solution worked ever, was to downgrade to the 2019 version.

**Comment by mlangkabel** [comment]
Hi @Hamid-K, thanks for the feedback. I didn't notice that #955 was closed, so i re-opened it now. Will close this one to avoid multiple conversations on the same thing.

**Comment by firestack** [comment]
Can the same be done for #1098 ?
