### ISSUE TITLE
When is the next release coming?

### ISSUE THREAD

**Issue by vinamrabenara** [CoatiSoftware/Sourcetrail#1166]

**Comment by mlangkabel** [comment]
In roughly two weeks. But the [2021.1.30 - Beta](https://github.com/CoatiSoftware/Sourcetrail/releases/tag/2021.1.30) should become available today.

**Comment by vinamrabenara** [comment]
> In roughly two weeks. But the [2021.1.30 - Beta](https://github.com/CoatiSoftware/Sourcetrail/releases/tag/2021.1.30) should become available today.

Sounds great! Would a .dmg would be added to beta release?

**Comment by egraether** [comment]
Yes, now with DMG: https://github.com/CoatiSoftware/Sourcetrail/releases/tag/2021.1.30
