### ISSUE TITLE
Python projects indexing problem

### ISSUE THREAD

**Issue by alex-bender** [CoatiSoftware/Sourcetrail#1167]
![image](https://user-images.githubusercontent.com/3628862/111305444-9f721100-865f-11eb-9d71-a2a066bf1428.png)
I'm unable to index python project and even can not see the error messages, because they disappear to fast and not written to any log.
Any ways to troubleshoot?

**Comment by mlangkabel** [comment]
Which Sourcetrail version are you using? What is you OS?

**Comment by alex-bender** [comment]
Sourcetrail Version 2020.2.43
Ubuntu 18.
It was working ok some time ago, then I've tired to install latest versions and now I can not index one of the projects.

*side note
after trying to tweak it somehow now I'm unable to launch it at all because of
`sourcetrail: symbol lookup error: /home/user/src/Sourcetrail/lib/libQt5XcbQpa.so.5: undefined symbol: FT_Property_Set`

**Comment by mlangkabel** [comment]
Did you already try to run the 2021.1.30 beta that we released yesterday?

**Comment by alex-bender** [comment]
Just tried to do that and looks like problem solved.
But, is it possible to have log messages persistent somewhere?
I didn't find it in logs dir/files.
Thanks!

**Comment by mlangkabel** [comment]
Thanks for testing with the latest version. 

You can enable logging in the preferences:

![image](https://user-images.githubusercontent.com/16242920/111376562-e54ec980-869f-11eb-94e8-5ae9755c0e2e.png)

If enabled, log messages should be written to a log file. You can find it by clicking the menu entry:

![image](https://user-images.githubusercontent.com/16242920/111376516-d700ad80-869f-11eb-8bb7-a350b0d01505.png)

Which seems to be working fine:

![image](https://user-images.githubusercontent.com/16242920/111376991-732ab480-86a0-11eb-9755-6fa65f7539c3.png)

**Comment by alex-bender** [comment]
Thanks a lot! Just found that feature myself as well. Thank you for providing such a great tool!
