### ISSUE TITLE
Adding edge legends on generated graph images

### ISSUE THREAD

**Issue by SiegfredRodriguez** [CoatiSoftware/Sourcetrail#1170]
Hello,

TLDR; Add legends for used edges on generated image.

I have always used your graph to image functionality and like it a lot.
However, typical use case at least for me is presenting this images to people who might not be aware of the sourcetrail edge legends.
It would be nice to add edge legends on generated images at least the ones in use in said image,

Thanks!

**Comment by mlangkabel** [comment]
Hey @SiegfredRodriguez, our legend is quite big (type "legend" into the search field to get there), but you could already save that as an image as well. What do you think?
