### ISSUE TITLE
Java comment parsing error

### ISSUE THREAD

**Issue by weltonrodrigo** [CoatiSoftware/Sourcetrail#1177]
Version 2019.4.102 (not using newer because of JVM problem).

# Observed (Line 2031):
![Captura de Tela 2021-05-24 às 13 45 31](https://user-images.githubusercontent.com/1644644/119380245-d899b380-bc96-11eb-94e0-2d2d62ed2007.png)

# Expected:
<img width="769" alt="Captura de Tela 2021-05-24 às 13 48 04" src="https://user-images.githubusercontent.com/1644644/119380269-e2231b80-bc96-11eb-9a20-83efbb81fd21.png">

I suppose the problem is the `//***` which gets interpreted as a multiline comment. Later on the file, a closing multiline comment restores the syntax.

Don't now if this is invalid java code, but Intellij parses it as a single line comment.

Thanks for the great, absurdly useful software!

Update:

It's just the syntax highlighting that seems wrong. Code was correctly indexed and symbols as clickable.

**Comment by mlangkabel** [comment]
Hi @weltonrodrigo, thanks for bringing this up. As far as I see the snippet that you posted is not really valid. As you suspected `/*` needs a `*/` to end the comment. Our syntax highlighting just uses simple regex, so I think that it won't be easy to cope with invalid code like IntelliJ does it.
