### ISSUE TITLE
Accept Path List Box in Visual Studio pathlist format(s), such as those in the 

### ISSUE THREAD

**Issue by PhilipOakley** [CoatiSoftware/Sourcetrail#1179]
When a project has many `#includes` which are to be added via the [Path Lists Box](https://www.sourcetrail.com/documentation/#PathListBox) it can be very tedious, especially if those values are already compactly represented in a Visual Studio pre-processor dependency, as seen in [Git-for-Windows](https://github.com/git-for-windows/git/wiki/Sourcetrail-code-viewer-and-linkage-to-Visual-Studio,-for-Git) wiki on how to link to Sourcetrail.

It shouldn't be necessary to do the text editor juggling if there's an already usable string, though with a different format, to paste directly into the box. I'd like to encourage more Git-for-Windows users to at least browse the code via Sourcetrail, so making things super easy would be a real benefit.

**Comment by mlangkabel** [comment]
In the path listbox you can click the "edit plain text" button (the pen icon in the lower right corner). Then you can enter all paths at once into a text box with a new line separator. Which format would you propose?

**Comment by PhilipOakley** [comment]
> In the path listbox you can click the "edit plain text" button (the pen icon in the lower right corner). Then you can enter all paths at once into a text box with a new line separator. 

Thanks for the suggestion

> Which format would you propose?

I was hoping that one could simply copy and paste from the relevant Visual Studio properties boxes, which in this case is/was a semicolon `;` separated list.

I've still to re-check as recent VS and Git build have updated some of the process to use CMakeLists.txt rather than a .sln.

So its that Source trail would recognise/allow/convert such a semicolon `;` separated list.  I suspect that I'd also got myself confused about which list I was talking about as my old instructions suggest I needed the `-D` prefix as well

The ultimate ideal is some form of scripting or command line mechanism so the Open Source projects could have a ready-to-go setup that would generate all the Sourcetrail input without "user failure"...

Ta.

**Comment by mlangkabel** [comment]
Sourcetrail is made to be used by people coming from different operating systems, programming languages, editors and build systems. We decided to go with `\n` as separator.
