### ISSUE TITLE
Documentation/Initial setup not idiot-proof enough/unclear Java library configuration info

### ISSUE THREAD

**Issue by build6** [CoatiSoftware/Sourcetrail#1193]
Hi all, just want to say - 

encountered sourcetrail online, video demo of functionality looked really good, downloaded to install and try out on my Win10x64 machine, and ... could not get it to work on a Java Android Studio project.  The idea behind sourcetrail looks really good but I think adoption/word-of-mouth would be improved if complete idiots (e.g. myself) could get it up and running easily.  For example I even had issue with errors about Java library "not found" etc., which took some doing since Java is in my path.  Have run into my time budget limit for this so am stopping.  If more handholding is available I suspect there'd be a lot more adoption.  

(is it an "Android" issue specifically?  If yes it might be helpful to explicitly state that sourcetrail does not function with Java-in-Android).

**Comment by mlangkabel** [comment]
Yes, it is an Android issue. Sourcetrail can only handle plain non-Android Java.
