### ISSUE TITLE
entire #include graph

### ISSUE THREAD

**Issue by cswrd** [CoatiSoftware/Sourcetrail#1196]
e.g.
[https://cdn2.hubspot.net/hubfs/582328/GrammaTech-Img/hello_hier.png](https://cdn2.hubspot.net/hubfs/582328/GrammaTech-Img/hello_hier.png)

Very nice to have:
- grouped by directory
- expand/collapse individual directories (dependency arrows expand/collapse, too)
- toggle user code only / no libs

Nice to have:
- hide certain files or directories / applying filters

Similar, but not identical feature request: #939 

Great software!

**Comment by mlangkabel** [comment]
We designed Sourcetrail by intention to focus the graph on an individual symbol. However, if you want to see a "path" between two symbols of your codebase, use the [Custom Trail](https://www.sourcetrail.com/documentation/#CustomTrail) dialog.
