### ISSUE TITLE
Typo in Link to Emacs Sourcetrail Plugin

### ISSUE THREAD

**Issue by waewos** [CoatiSoftware/Sourcetrail#1204]
at `plugins/emacs/README.md`

> Link to the repository: `[emacs-sourcetrail](https://github.com/CoatiSoftware/emacs-sourcetiral)`.

-> `https://github.com/CoatiSoftware/emacs-sourcetrail`

**Comment by mlangkabel** [comment]
Looks fine to me: https://github.com/CoatiSoftware/Sourcetrail/blob/master/ide_plugins/emacs/README.md
