### ISSUE TITLE
Is there any thing i can do to make sourcetrail not only show direct relations of active symbols?

### ISSUE THREAD

**Issue by rxh1999** [CoatiSoftware/Sourcetrail#1216]
the situation is, when i click class A's method ma, then click method mb inside ma, then back to ma, click another method mc inside ma, the node represent mb will disapper, is there any thing i can do to make sourcetrail not hide mb?
i found descriptions in tutorial, "Sourcetrail keeps a strongly focused view on your code. This focus only includes the currently active symbol and its direct relations", seems sourcetrail only show direct relations of currently active symbol, is there an exception?

**Comment by mlangkabel** [comment]
There is no such feature, but there is a request for it: https://github.com/CoatiSoftware/Sourcetrail/issues/50
