### ISSUE TITLE
Move the Project to KDE Umbrella to avoid discontinuing?

### ISSUE THREAD

**Issue by tcanabrava** [CoatiSoftware/Sourcetrail#1220]
Hello

I use sourcetrail to teach programming for a few years already, and I'm quite sad that this will be discontinued. Would the developers be willing to move the software to the kde sdk infrastructure to avoid it being discontinued?

**Comment by mlangkabel** [comment]
Thanks @tcanabrava for the suggestion. We discussed this here: #1214.
