### ISSUE TITLE
Add hints for inherithed and overridden methods

### ISSUE THREAD

**Issue by MatteoRagni** [CoatiSoftware/Sourcetrail#1223]
Hi there, 

SourceTrail is really fantastic, keep up with the great job.

I'm here to suggest a feature to improve (IMHO) the visualization. This can be useful in C++, at least for classes with a quite big interface. It can be useful to show on class methods in the graph some graphical suggestion for inherited and overridden methods (something like a slightly different color, a dashed border or a small icon on the badge of the method)

What do you think?

(I'm on version 2021.1.31-64bit DB v.25 for linux)

**Comment by mlangkabel** [comment]
Thanks for the suggestion, but the spirit of Sourcetrail is to keep the interface easy to read. If there is lots of different colors ur other UI dimensions that the user needs to remember, it is getting much harder to use. The philosophy of Sourcetrail is "focus" and "info on demand". So if the user focusses (clicks) on the method of interest, Sourcetrail then shows the edges to overridden/overriding methods.
