### ISSUE TITLE
Define custom log directory in preferences

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/Sourcetrail#156]
Implementation suggestion:
* Add getter/setter to `ApplicationSettings` that uses the standard path as default.
* Add file path selection UI to `QtProjectWizardContentPreferences` for selecting the log directory path

**Comment by egraether** [comment]
Also allow changing the log file path to allow adding exception for virus scanner.

**Comment by mlangkabel** [comment]
Implemented by @Waqar144 and applied with merge of pull request #900
