### ISSUE TITLE
Support non-monospace fonts in UI

### ISSUE THREAD

**Issue by ffuugoo** [CoatiSoftware/Sourcetrail#179]
After updating to Coati v0.8.0 on one of my machines I have this:
![coati-rendering-issue-1](https://cloud.githubusercontent.com/assets/2725918/18265016/e82a713c-7456-11e6-82a3-4320ce1f0a48.png)
_the blur on the picture is just me hiding potentially sensitive stuff_
![coati-rendering-issue-2](https://cloud.githubusercontent.com/assets/2725918/18265015/e8280302-7456-11e6-84d3-c27c9c77a69d.png)

Previous release (v0.7.0.22) worked like a charm.

My assumption is that the issue have to do something with Intel video drivers.
1. Intel drivers tend to have problems like this (e.g., there is well known issues with various web-browsers)
2. I don't have any problems on my other machine with Nvidia video (apart from different video-drivers, I have almost identical software set-ups on all machines)

_I also checked package update history, and as I see, there was **no** video-driver updates around the moment I switched from v0.7.0.22 to v0.8.0._

Here is some more information about my system:

**distro:** Arch Linux

**uname -a:** Linux <hostname> 4.7.2-1-ARCH #1 SMP PREEMPT Sat Aug 20 23:02:56 CEST 2016 x86_64 GNU/Linux

**CPU model:** Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz

**xf86-video-intel package version:** 1:2.99.917+697+g12c14de-1 (have to be [this](https://cgit.freedesktop.org/xorg/driver/xf86-video-intel/commit/?id=12c14deb40fb4a9488d11ce53c5ce956c776a742) commit)

I'll also try to apply common fix for such problems (tweak Intel driver config) and report the results ~~soon~~ tomorrow.

**Comment by titovroman** [comment]
Well, I re-tested everything more carefully, and:

1. I suddenly found out that the bug is reproducible even with Coati 0.7.0.22 now.
2. Seems like bug is not related with Intel drivers at all. I re-tested Coati 0.7.0.22 and 0.8.0 with 3 last version of xf86-video-intel package and the issue was still there. Sorry for preliminary conclusions and misguidance.

Now I assume that bug somehow related to Qt libs bundled with Coati. I replaced bundled Qt libs with symlinks to my system's native ones and all issues got resolved. It even fixed issues with fonts (as you can see, Coati on my screenshots use some dreadfully awful fonts; it's _beautiful_ now). Probably some library which bundled Qt libs depend on was updated and *this* actually broke things.

For now, I'll use this approach (with symlinks), however, I'll still try to compare package versions on both of my machines. Maybe I'll find some insights on the issue.

**Comment by st4ll1** [comment]
Hey @titovroman. 
I looked into it yesterday and came to the same conclusion as you, something is wrong with the bundle Qt Libs.
The libs will be replaced in the next release. 

You mentioned you reproduced this with Coati 0.7.022. Did you use the libs from Coati 0.8? If not how did you reproduce it?

**Comment by titovroman** [comment]
OMG, I'm such a retard. It **is** reproducible on my Nvidia machine as well. It's just not very notable sometimes (e.g., if the search-string is not long enough). Such a shame... -_\

> Did you use the libs from Coati 0.8?

Nope. Such idea would be too insane for me. (However, I see some sense in it on the second thought.)

> If not how did you reproduce it?

Basically, nothing. Just downloaded Coati 0.7.0.22 to properly re-check things and faced the issue on the very first run. And to clarify things, I wiped my ~/.config/Coati dir before running different versions of Coati and also used created separate Coati-projects for 0.7.0.22 and 0.8.0.

So, well, one more point to "Qt libs and/or their interaction with other part of the system" theory.

**Comment by st4ll1** [comment]
> So, well, one more point to "Qt libs and/or their interaction with other part of the system" theory.

So, i did some more testing with the 0.8 release, it looks like the problem is between the shipped Qt Libs and some Arch Linux system libs.
I tested it on with Ubuntu and Fedora and it looks fine there, on my Arch Linux machine i have the same problem.

**Comment by st4ll1** [comment]
It seems like it a completely different problem at all. It look like the problem occurs if non mono-space fonts are used. The default font "Source Code Pro" should look fine, but others like "DejaVu Sans" causes the problem.
@titovroman can you confirm  this?

**Comment by titovroman** [comment]
> @titovroman can you confirm this?

Checked. Confirm.

**Comment by egraether** [comment]
We currently only show mono-space fonts in font selection UI. Changed this to a feature request now.

**Comment by egraether** [comment]
Supporting non-mono-space-fonts would make graph layout less readable.
