### ISSUE TITLE
List recently used project paths within project setup

### ISSUE THREAD

**Issue by vtky** [CoatiSoftware/Sourcetrail#212]
Hey,

Would be nice to have a list of recently used project paths just to speed things up a little

![image](https://cloud.githubusercontent.com/assets/9355200/18861742/22e181bc-84ba-11e6-9f4f-3f2fe01ea1f4.png)

**Comment by egraether** [comment]
using a path of a recent project that already exists as the location for a new project does not make sense. This issue should be circumvented by #802
