### ISSUE TITLE
Keyboard navigation for code view

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/Sourcetrail#214]
e.g. arrow keys or vim-like HJKL

**Comment by AnomalRoil** [comment]
+1
Most IDE nowadays allow mouse-less usage, it's annoying to have to rely on the mouse while using SourceTrail. I'd say that even the Graph view could benefit from keybindings such as "hint based navigation" (like Vimperator or Vimium do in a browser.)

**Comment by egraether** [comment]
Do you have a specific keyboard navigation concept in mind?

**Comment by egraether** [comment]
Fixed with #935
