### ISSUE TITLE
IDE Plugin 'Set active token' should send token name instead of cursor location

### ISSUE THREAD

**Issue by wrongway88** [CoatiSoftware/Sourcetrail#262]
As soon as the file is edited, the cursor location does not fit the token location stored in Coati (not until refresh). Makes usage during editing cumbersome...

**Comment by mlangkabel** [comment]
Closing because if you have the following code:
```c++
Foo foo;
Bar bar;
foo.clear();
bar.clear();
```
and the IDE sends the symbol name `clear`, Sourcetrail would still not know which `clear` to activate.
