### ISSUE TITLE
Support flatpak/snaps/appimage packages for Linux installs

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/Sourcetrail#279]
http://flatpak.org/

**Comment by st4ll1** [comment]
since flatpak is not the only way to go maybe consider 
http://snapcraft.io/  
and
http://appimage.org/ 
too

**Comment by probonopd** [comment]
Providing a Coati [AppImage](http://appimage.org/) would be really easy. In fact I have generated one but since I am not sure whether it Coati is redistributable, I don't provide it for download. But you can generate your own on any 64-bit Ubuntu or debian system:
```
wget -c https://github.com/probonopd/AppImages/raw/master/recipes/meta/Recipe
bash Recipe Coati
```
The resulting AppImage should run on most 64-bit desktop distributions (not just Ubuntu and debian).

**Comment by egraether** [comment]
+1 via Slack
AppImage Docker sample: https://github.com/jeandet/CentOS_7_Qt_AppImage/blob/master/Dockerfile

**Comment by TTimo** [comment]
A flatpak one would be nice, I think it's the most mature and generally supported solution.

**Comment by digitalcoyote** [comment]
I'd be willing to work on a flatpak package that could be published to FlatHub. I could hook it up to my AppVeyor account like I did with the chocolatey package.  Linux Mint (my OS of choice) supports FlatHub as a default installation source so it would help me out personally as well to have it there. 

Id be willing to assist with other formats that are supported across distributions as well (but it sounds like there be some making good progress on those already).

**Comment by probonopd** [comment]
@digitalcoyote didn't the AppImage work for you or do you have other reasons why you prefer a Flatpak?

**Comment by digitalcoyote** [comment]
> @digitalcoyote didn't the AppImage work for you or do you have other reasons why you prefer a Flatpak?

Honestly, it's just what I'm used to using.

**Comment by egraether** [comment]
@digitalcoyote If you want to work on a flatpak, please go for it! We have little expertise on which of these formats are better or worse. From [this comparison](https://github.com/AppImage/AppImageKit/wiki/Similar-projects#comparison) it looks though that AppImage is more flexible and better compatible with older distributions.

**Comment by egraether** [comment]
Finally took some time to look into this. I opted for AppImage, since it is recommended by the [Qt docs](https://wiki.qt.io/Deploying_a_Qt5_Application_Linux) and using [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) made this pretty easy.

A beta version is already available [here](https://github.com/CoatiSoftware/Sourcetrail/releases/tag/2020.1.131). I tested on Ubuntu 16.04 and 18.04, where it worked without issues. We plan to release this with our next major version, along with our usual download package. Please test and let me know if you experience any issues.

**Comment by probonopd** [comment]
Works nicely on Xubuntu 18.04:

![](https://user-images.githubusercontent.com/2480569/77622557-631d4080-6f36-11ea-8960-f07c285f32f3.png)

**Comment by bam80** [comment]
Just for reference: "Can't update AppImage" #1055

**Comment by bam80** [comment]
> I'd be willing to work on a flatpak package that could be published to FlatHub.

@digitalcoyote have you had a chance to make it happen?

**Comment by digitalcoyote** [comment]
@bam80  I have not. It kept getting bumped down my priority list. I'll get to it eventually but if someone else wants to take a stab at it, I don't mind taking a step back

**Comment by bam80** [comment]
Could we add QtWayland to the AppImage build? #1017

**Comment by probonopd** [comment]
I have never tried it, but it is worth a try. Should be something along the lines of

```
mkdir -p appdir/usr/plugins/platformplugins/
cp /usr/lib/x86_64 /usr/plugins/platformplugins/qtwayland.so  appdir/usr/plugins/platformplugins/

# If you also want to deploy its dependencies, do something like this - but I don't think you want to bring Wayland libs to non-Wayland systems, so probably it's best NOT to do this
linuxdeployqt AppDir/usr/share/applications/sourcetrail.desktop -qmake=$Qt5_DIR/bin/qmake -ignore-glob=*python* -appimage -executable=appdir/usr/plugins/platformplugins/qtwayland.so
```
