### ISSUE TITLE
keyboard navigation for graph

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/Sourcetrail#327]

**Comment by AnomalRoil** [comment]
+1

**Comment by egraether** [comment]
Do you have a specific keyboard navigation concept in mind?

**Comment by AnomalRoil** [comment]
As mentioned in the other issue, hint based navigation "à la vimperator" seems me well suited to the task:  ![image](https://user-images.githubusercontent.com/10077203/33210856-1c68ef8c-d11c-11e7-8a5c-bdf1618678f8.png)

**Comment by egraether** [comment]
Fixed with #935
