### ISSUE TITLE
Menu action for graph "Save as Image"

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/Sourcetrail#426]

**Comment by mlangkabel** [comment]
Which menu shall this be added to?

**Comment by egraether** [comment]
Edit, I guess

**Comment by miltolstoy** [comment]
Hi!
Please assign this issue to me, I'll handle it.

As I see, there is no problem to convert `QtGraphicsView` to `QPixMap` and save on filesystem. I also found an entry point for this action - "Edit" menu setup code in main window. I spent some time digging how to reach `QtGraphicsView` from `QtMainWindow`, but don't have any significant result yet. 
As I see, some actions are implemented by messages sending. If message should be dispatched, who should handle it?
Any advice will be highly appreciated.

**Comment by egraether** [comment]
>  I spent some time digging how to reach `QtGraphicsView` from `QtMainWindow`, but don't have any significant result yet.

This is where we use messages. Please add a new message type, dispatch it in `QtMainWindow` when the save action is triggered and listen on it in `QtGraphicsView`, which has access to the graph pixmap.

**Comment by miltolstoy** [comment]
Okay, one more question.
There is already implemented `QImage QtGraphicsView::toQImage()` method which captures full graph to image and adds export notice. Also there is a parent `QPixmap QGraphicsView::grab()` method that captures that part of a graph, which is currently displayed (it can be a small part if graph is zoomed or graph is huge enough).
Which capturing should be used?

**Comment by egraether** [comment]
There already is a *Save as Image* option in the context menu of the Graph. This issue is about reusing this action, but trigger it from the Window menu. Just reuse the implementation of *Save as Image* from the context menu please.
