### ISSUE TITLE
Setting indexed headers for Compilation Database Project causes non-indexed symbols

### ISSUE THREAD

**Issue by mlangkabel** [CoatiSoftware/Sourcetrail#571]
This is only the case if the compilation database defined header search paths with `-I` and multiple header files share the same name but different include paths

**Comment by ngn999** [comment]
did u mean Sourcetrail 2018.2.23?

**Comment by mlangkabel** [comment]
No, it's fixed with 2018.2.28. So, once we release a higher version than that, the bug will be gone.
