### ISSUE TITLE
DMG not mountable on macOS 10.11.6 since 2018.3.13

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/Sourcetrail#619]
The dmg is created by running the `bundle_install.sh` script within the build directory. The file is generated by cmake from `bundle_install.sh.in`. 

The command to create it is:
```
PACKAGE_DIR=<path_to_directory_containing_app_bundle>
hdiutil create ${PACKAGE_DIR}_macOS_64bit.dmg -volname ${PACKAGE_DIR} -srcfolder ${PACKAGE_DIR}
```
It is executed on macOS Mojave 10.14.5 (18F132)
What is going wrong here?

**Comment by egraether** [comment]
Asked reporter if 2018.4.0 beta download works.

**Comment by egraether** [comment]
Reporter updated macOS and can't test anymore. Closing.

**Comment by biasix** [comment]
Same problem here. Same macOS version. After downgrade from Mojave on a fresh El Capitan install. Followed standard instructions from Apple for recovery for this type of issue. No resolve.

Tried all current DMGs from the downloads page.

2017.2.0 - 2018.2.23 all do mount
2018.2.36 - 2019.1.11 won't mount

Error message 
"The following disk images couldn't be opened"
Image / Reason
(the name of the image) / image not recognized
(the name of the image) / no mountable file systems

Thinkable cause. Incompatibility between DMGs generated in Mojave and El Capitan suspected. 

Suggested resolution: Build DMG on lowest MacOS version possible.

**Comment by egraether** [comment]
Thanks for reporting!

We currently don't have any ready to use macOS 10.11 or older around.
As a workaround, can you unpack the DMG on another Mac?

**Comment by biasix** [comment]
Unfortunately no. But I'm OK with the older version so far. Thanks. 

Let me know if I can help with testing at some point then. Glad to help.

**Comment by egraether** [comment]
I uploaded the new build also as `.zip` file here: https://www.sourcetrail.com/downloads#extra
Please let me know if the build is useable.

**Comment by biasix** [comment]
It worked. Here is my full report:

Tried Sourcetrail 2019.2.39 DMG first. Doesn't mount.

Unpacked Sourcetrail 2019.2.39 ZIP. Moved Sourcetrail.app to applications. Replaced old version. Opened it. Verifying took longer than expected, but the app opened.

Then I opened a C++ project from the 2018.2.23 version. Sourcetrail reports I should reindex after migration to latest version.

From there, usability issues. But that's another subject. (Couldn't figure out, how to enforce reindex. No worries here, we are just testing.)

Then I simply opened tictactoe.py to find out if everything is working as expected, if I  can browse the code. 

So far El Capitan wise everything seems in a working condition.

Minor Bug it seems, I need to kill the app to close it each time. I'm not sure though as of yet, if it's sourcetrail or my system. But I recall something similar on Mojave with an older sourcetrail version, where it took very long time until the app closed.

**Comment by lovasoa** [comment]
I have the same problem with the dm file from [this github release](https://github.com/CoatiSoftware/Sourcetrail/releases/tag/2019.4.61) :

<img width="483" alt="image" src="https://user-images.githubusercontent.com/552629/69153885-4b90ff80-0adf-11ea-9676-73ad888d3ba8.png">

**Comment by egraether** [comment]
Added `.zip` for macOS to releases as workaround again: https://github.com/CoatiSoftware/Sourcetrail/releases/tag/2019.4.61

**Comment by phil-blain** [comment]
Hi, I'm having a slightly different problem: I'm on 10.11.6 and downloaded the zip archive, but after moving  `Sourcetrail.app` to my `/Applications` folder, the app doesn't open at all... I click on it, it appears in the Dock for a few milliseconds and then disappears...

**Comment by egraether** [comment]
What output do you get when starting from Terminal?: `/Applications/Sourcetrail.app/Contents/MacOS/Sourcetrail`

**Comment by phil-blain** [comment]
Thanks for the quick reply! 
~~~
$ /Applications/Sourcetrail.app/Contents/MacOS/Sourcetrail
Sorry, "Sourcetrail" can not be run on this version of macOS. Qt requires macOS 10.12.0 or later, you have macOS 10.11.6.
~~~

That's clear enough... I guess a recent version of Sourcetrail updated Qt to a version that drops support for 10.11.. I'll try installing an older version.

**Comment by phil-blain** [comment]
I can't find any binary assets for tags before 2019.4.61, were they removed ? are they available somewhere ?

**Comment by phil-blain** [comment]
@egraether Regarding the unmountable disk image: this is due to the fact that `hdiutil` defaults to the new APFS file system on High Sierra and higher. You need to use `-fs HFS+` to create the disk image in HFS+ format that will be readable on Sierra and lower.

Reference:
https://davidnelson.net/2017/09/high-sierra-dmg/

**Comment by egraether** [comment]
Awesome, thank you!
