### ISSUE TITLE
Can't use python environment - binary unsafe.

### ISSUE THREAD

**Issue by apoorv-kumar** [CoatiSoftware/Sourcetrail#697]
Hi, I can't find any documentation around the error - 

WARNING: The provided environment path "/home/apoorv/sandbox/venv/test_env" does not specify a functional Python environment (details: "The python binary is potentially unsafe."). Using fallback environment instead.".

I'm using Python3.5 environment on Ubuntu18.04.

**Comment by mlangkabel** [comment]
@egraether: didn't you encounter this error, too?

**Comment by egraether** [comment]
Yes, I think the problem was that there was no binary named `python` in the directory. I made a copy of my `python36` binary and named it `python`. I think it helped with the problem, but I had a different one to fix then.

**Comment by apoorv-kumar** [comment]
@egraether thank you for your response. I made sure that I have a 'python' binary in my env/bin but it doesn't seem to fix it. Unfortunately even verbose logs don't tell me more about the issue. Guess I'll have to wait to try it out for my projects.

**Comment by egraether** [comment]
@apoorv-kumar Maybe it is a Sourcetrail execution environment problem. Did you start Sourcetrail directly from Terminal? If not, please try that.

**Comment by apoorv-kumar** [comment]
@egraether I did open the 'Sourcetrail' binary from terminal.

**Comment by mlangkabel** [comment]
We just released Sourcetrail 2019.2.39, which now displays validity information for the specified python environment directly in your project settings, so it's much faster for you to try different approaches. Can you for example try to specify the path directly to the Python executable of the virtual environment?

**Comment by pmneve** [comment]
Am having same issue.
`/Users/nevep/.pyenv/bin/versions/2.7.9/bin/python` specified directly in the environment textbox.
and any other versions I try show 'binary is potentially unsafe'

**Comment by xanni** [comment]
I'm having the same issue.

**Comment by xichen-de** [comment]
Same here with a conda environment.

**Comment by tdamsma** [comment]
Same with virtualenv installed environment on OS X / Sourcetrail 2019.4.61.

**Comment by petevdp** [comment]
Same here with virtualenv on Ubuntu 19.04

**Comment by XVicarious** [comment]
Okay, so I have tracked this issue down to [this](https://jedi.readthedocs.io/en/latest/docs/api.html#jedi.find_virtualenvs). Basically as this stands unless you change ownership on the python executable to root, a virtual environment won't work due to Jedi by default requiring an environment to be "safe". [This line](https://github.com/CoatiSoftware/SourcetrailPythonIndexer/blob/master/indexer.py#L28) needs to be changed to include `safe=False` to allow virtual environments based on my quick research.

**Comment by mlangkabel** [comment]
@XVicarious: Thank you for creating the new issue on the Python indexer repo and linking it here. 

As this issue is fully within the scope of the Python indexer, we should continue disucssing it over at https://github.com/CoatiSoftware/SourcetrailPythonIndexer/issues/59.
