### ISSUE TITLE
bugs with version numbers on macOS

### ISSUE THREAD

**Issue by core-code** [CoatiSoftware/Sourcetrail#730]
bug 1.) the version number of the 2019.3.46 has not been updated properly. the 'CFBundleVersion' of the newest release is still '2019.3-42-gfcc47e6a'

bug 2.) the version number of Sourcetrail is not visible in the macOS Finder when inspecting Sourcetrail via 'Get Info' or 'Column View' because the 'CFBundleShortVersionString' is actually empty. it is only visible via 'QuickLook' but as written above it is actually the old, wrong version number thats contained in the newest version

**Comment by core-code** [comment]
<img width="443" alt="Screenshot 2019-09-04 at 19 19 59" src="https://user-images.githubusercontent.com/1261954/64276944-6aa0dc00-cf49-11e9-95c8-252d12983617.png">
<img width="264" alt="Screenshot 2019-09-04 at 19 20 06" src="https://user-images.githubusercontent.com/1261954/64276945-6b397280-cf49-11e9-8c1a-d54c5b5f2ffb.png">
<img width="603" alt="Screenshot 2019-09-04 at 19 21 28" src="https://user-images.githubusercontent.com/1261954/64276946-6b397280-cf49-11e9-9692-c708bd81a905.png">
<img width="567" alt="Screenshot 2019-09-04 at 19 20 18" src="https://user-images.githubusercontent.com/1261954/64276947-6bd20900-cf49-11e9-829b-4943db34774c.png">

**Comment by core-code** [comment]
bug 3: the Info.plist also contains the keys 'CFBundleGetInfoString' and 'CFBundleLongVersionString'. both of them have been deprecated for more than 10 years and should be removed

**Comment by egraether** [comment]
Thanks for reporting, will look into it!

**Comment by egraether** [comment]
Fixed with 2019.4.57

**Comment by core-code** [comment]
thanks i can confirm it is fixed
