### ISSUE TITLE
Support for Android Studio Project

### ISSUE THREAD

**Issue by ckddls1321** [CoatiSoftware/Sourcetrail#736]
Currently I'm using source trail for visualize code.
On Android studio, I added compile database json for source trail.
It works like a charm.
Any idea to add source group of java with android studio projects? 

Also I have more questions.
1) Is there any features for jni indexing java -> jni -> c++
2) Does source trail support cross compile? 
- It seems just parse source and headers on compile database json.
So predefined flags on CMakeLists with ARM remains unindexed symbol. 
How can I set flags and headers on CMakeLists.txt when makes compile database json.

**Comment by mlangkabel** [comment]
Hi,
so if I understand correctly, 
* you are working on C++ code and you can export the compilation database from android studio and use it for your project setup
  * great!
* you are also working on java code using android studio and are wondering how to set up your sourcetrail project 
  * right now we only offer gradle and maven support for importing a project configuration. so you need to set up the project using the "Empty Java Source Group" and just add the source files and the dependencies
* you have a project that uses JNI to call java code from c++ or vice versa
  * you can make one sourcetrail project that has both, c++ and java source groups, however the linking between the languages (e.g. `CallStaticVoidMethod(...)` etc.) is not recorded.
* you have a c/c++ project that you compile for a different architecture. Indexing that project works fine, but there are still some "non-indexed symbols" that are defined in the standard library that you are using for that architecture.
  * just add the paths to where those symbols are defined to your project's "Header Files & Directories to Index".

**Comment by ckddls1321** [comment]
Thank you. I will handle non-indexed symbols through define standard library header path for architecture. I hope someday it will support cmake include directories automatically when cross compile. Anyway, it solved problem.
