### ISSUE TITLE
Popup problem in "Finished indexing" dialogue

### ISSUE THREAD

**Issue by mauline** [CoatiSoftware/Sourcetrail#740]
Given that I have a source with indexing errors like the one from #739:

The "Finished Indexing" dialogue shows a red dot and says "1 Error" with a question mark in a circle behind it. When hovering the mouse over the question mark it says "help" but when clicking on it nothing happens.

When the dialogue is closed with "OK" a number of help screens appear one for each click on the question mark. If you click three times on the question mark, you will have to close three help dialogues after closing the "Finished Indexing" dialogue.

**Comment by mlangkabel** [comment]
Hi @mauline, wow, thanks for reporting that! We can reproduce it on Windows and will take a look.

**Comment by mlangkabel** [comment]
Fixed by merge of pull request #904.
