### ISSUE TITLE
Cannot run Sourcetrail on macOS 10.15

### ISSUE THREAD

**Issue by acgetchell** [CoatiSoftware/Sourcetrail#743]
Cannot run Sourcetrail on macOS 10.15:

![Screen Shot 2019-10-11 at 6 15 00 PM](https://user-images.githubusercontent.com/434849/66692438-2e048680-ec53-11e9-9fac-40a4e5f8d1a6.png)

You need to notarize your app.

https://support.apple.com/en-us/HT202491

**Comment by egraether** [comment]
script integration of notarization: https://developer.apple.com/documentation/xcode/notarizing_your_app_before_distribution/customizing_the_notarization_workflow

**Comment by matthewadams** [comment]
I just hit this, too.  :(

**Comment by egraether** [comment]
@acgetchell @matthewadams  I notarized Sourcetrail.app of release 2019.4.61 now. Please [download the latest release](https://github.com/CoatiSoftware/Sourcetrail/releases) and check if this works now please. **Even if you already downloaded it, please download again, I changed the build today**

**Comment by acgetchell** [comment]
Unfortunately, still not resolved. I deleted the cached download and just downloaded a fresh copy:
```
╭─adam@campus-109-155 ~/Library/Caches/Homebrew/downloads 
╰─$ brew cask info sourcetrail
sourcetrail: 2019.4.61
https://www.sourcetrail.com/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/sourcetrail.rb
==> Name
Sourcetrail
==> Artifacts
Sourcetrail.app (App)
╭─adam@campus-109-155 ~/Library/Caches/Homebrew/downloads 
╰─$ brew cask install sourcetrail                    
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Downloading https://www.sourcetrail.com/downloads/2019.4.61/osx/64bit
                    -=O=-                  #     #     #    #                 
==> Verifying SHA-256 checksum for Cask 'sourcetrail'.
==> Installing Cask sourcetrail
==> Moving App 'Sourcetrail.app' to '/Applications/Sourcetrail.app'.
🍺  sourcetrail was successfully installed!
```
But I still get:

<img width="532" alt="Screen Shot 2019-11-20 at 2 19 48 PM" src="https://user-images.githubusercontent.com/434849/69283309-06cd9d00-0ba1-11ea-9ecb-7b3a1bad4fbf.png">

**Comment by egraether** [comment]
@acgetchell Sorry, I forgot to update the build on our server, because we are currently redirecting all visitors to GitHub releases, so I only changed the macOS build on GitHub releases.

I just updated the build on our server as well. Can you try again please?

**Comment by acgetchell** [comment]
Tried it, the checksum doesn't match. Would you verify that this is the correct file?

```
╭─adam@hapkido ~/Library/Caches/Homebrew/downloads 
╰─$ brew cask install sourcetrail      
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
No changes to formulae.

==> Downloading https://www.sourcetrail.com/downloads/2019.4.61/osx/64bit
-=O=-                                                                  #  # ##
==> Verifying SHA-256 checksum for Cask 'sourcetrail'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'sourcetrail' does not match.
Expected: c296b7d0ad486eed8a0f252d392fb30325820458b7a88c30cc18dce4b62e5665
  Actual: 03ffaa3152121d2131229b5df5599967c5c1b30fbe489b08dafeba07806fe1ac
    File: /Users/adam/Library/Caches/Homebrew/downloads/49533542f2ccfa450488c14c2a03d81666619261388a717ad606c4640f966dcb--Sourcetrail_2019_4_61_macOS_64bit.dmg
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md
```

**Comment by egraether** [comment]
Yes, that one is correct
```
$ shasum -a 256 Sourcetrail_2019_4_61_macOS_64bit.dmg 
03ffaa3152121d2131229b5df5599967c5c1b30fbe489b08dafeba07806fe1ac  Sourcetrail_2019_4_61_macOS_64bit.dmg
```

I don't know who maintains homebrew for Sourcetrail downloads. We only put the downloads on our website. On macOS you should be safe anyhow, because the `Sourcetrail.app` bundle is code signed by `Coati Software KG`.

**Comment by acgetchell** [comment]
I created a pull request with the new checksum here:

https://github.com/Homebrew/homebrew-cask/pull/72955

**Comment by egraether** [comment]
And does it work now?

**Comment by acgetchell** [comment]
They haven't accepted the pull request yet.

**Comment by acgetchell** [comment]
Fixed.

```
╭─adam@hapkido ~ 
╰─$ brew cask install sourcetrail
==> Downloading https://www.sourcetrail.com/downloads/2019.4.61/osx/64bit
## #                                                  -=O=-                   
==> Verifying SHA-256 checksum for Cask 'sourcetrail'.
==> Installing Cask sourcetrail
==> Moving App 'Sourcetrail.app' to '/Applications/Sourcetrail.app'.
🍺  sourcetrail was successfully installed!
```
