### ISSUE TITLE
XUbuntu 19.10 Compile Issues [EDITED]

### ISSUE THREAD

**Issue by salamanderrake** [CoatiSoftware/Sourcetrail#749]
Running XUbuntu 19.10 with boost 1.97, but Sourcetrail requires boost 1.98.

Running 
```
mkdir build
cd build
cmake ..
```  

Getting (relevent) out put.

```   
Could NOT find Boost: Found unsuitable version "1.67.0", but required is at
  least "1.68" (found /usr/include)
```

**Comment by egraether** [comment]
You could try to change the required version to 1.67 in the root CMakeLists.txt file and see if that works.

**Comment by hemebond** [comment]
> You could try to change the required version to 1.67 in the root CMakeLists.txt file and see if that works.

This got around the original error for me, but I was unable to compile (`undefined reference to symbol` error) so I'm not sure if it's a solution or not.

**Comment by salamanderrake** [comment]
I changed the title because there are several issues on X/Ubuntu 19.10.
1. Modified the CMakeFiles.txt to boost dependency 1.67
2. Had to create a symlink for missing /usr/lib/x86_64-linux-gnu/libglapi.so to /usr/lib/x86_64-linux-gnu/libglapi.so.0 as the CMake couldn't find libglapi.so
3. Error as @hemebond said when compiling
```
 make
[  1%] Built target Sourcetrail_lib_utility
[ 53%] Built target Sourcetrail_lib
check/update version number
-- Found Git: /usr/bin/git (found version "2.20.1") 
fatal: No names found, cannot describe anything.
-- Version: ..
[ 53%] Built target versionnumber
[ 53%] Automatic MOC for target Sourcetrail_lib_gui
[ 53%] Built target Sourcetrail_lib_gui_autogen
[ 89%] Built target Sourcetrail_lib_gui
[ 90%] Linking CXX executable app/sourcetrail_indexer
/usr/bin/ld: libSourcetrail_lib.a(SharedMemory.cpp.o): undefined reference to symbol 'sem_open@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/Sourcetrail_indexer.dir/build.make:96: app/sourcetrail_indexer] Error 1
make[1]: *** [CMakeFiles/Makefile2:289: CMakeFiles/Sourcetrail_indexer.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

Will add more issues/fixes here as I investigate whats going on.

**Comment by danieljabailey** [comment]
For me I can get past that link error on Ubuntu 18.04 with the following patch.
But this still doesn't let me build the whole project, I suddenly get _lots_ of _other_ undefined reference errors, and my CMake skills are not good enough to know how to fix them.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 70f8c337..ba7051eb 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -530,6 +530,7 @@ target_link_libraries(
        $<$<BOOL:${BUILD_CXX_LANGUAGE_PACKAGE}>:${LIB_CXX_PROJECT_NAME}>
        $<$<BOOL:${BUILD_JAVA_LANGUAGE_PACKAGE}>:${LIB_JAVA_PROJECT_NAME}>
        $<$<BOOL:${BUILD_PYTHON_LANGUAGE_PACKAGE}>:${LIB_PYTHON_PROJECT_NAME}>
+       rt pthread
 )
 
 if (APPLE)
```

**Comment by salamanderrake** [comment]
Its the position of your libraries and you are missing one.

```diff --git a/CMakeLists.txt b/CMakeLists.txt
index 8cc92bc4..4df8da8a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -102,7 +102,7 @@ set(Boost_USE_MULTITHREAD ON)
 set(Boost_USE_STATIC_LIBS ON CACHE BOOL "Set to ON to force the use of the static libraries.")
 set(Boost_USE_STATIC_RUNTIME OFF)
 
-find_package(Boost 1.68 COMPONENTS system program_options filesystem date_time REQUIRED)
+find_package(Boost 1.67 COMPONENTS system program_options filesystem date_time REQUIRED)
 
 
 # Qt ---------------------------------------------------------------------------
@@ -218,7 +218,7 @@ target_include_directories(${LIB_UTILITY_PROJECT_NAME} SYSTEM
 )
 
 if(UNIX)
-	target_link_libraries(${LIB_UTILITY_PROJECT_NAME} ${Boost_LIBRARIES} Qt5::Widgets Qt5::Network)
+	target_link_libraries(${LIB_UTILITY_PROJECT_NAME} ${Boost_LIBRARIES} Qt5::Widgets Qt5::Network dl rt pthread)
 else()
 	target_link_libraries(${LIB_UTILITY_PROJECT_NAME} ${Boost_LIBRARIES} Qt5::Widgets Qt5::Network Qt5::WinExtras)
 endif()
```

With the latest pull (1e870e9a257e2aa3dc06ee11186be2875f8f538d) it compiles fine but I can't build the CXX Indexer as it supports CLang 8 only, and UBuntu ships with CLang 9.

**Comment by mlangkabel** [comment]
If it helps: We already have an issue (#763) open for switching to Clang 9 and will pull / work on the respective changes as stated :)

**Comment by salamanderrake** [comment]
@mlangkabel Yeah, its working now, #762 did the trick.

**Comment by dackdel** [comment]
Not directly related but I ran this on pop os which is a 19.10 flavour of ubuntu. Worked great except the ui was way oversized, tried to fix it by scaling it down via preferences but I went too small, now i cant fix it.

**Comment by egraether** [comment]
@dackdel If the scaling breaks the UI, you need to delete `~/.config/sourcetrail/~ApplicationSettings.xml` or remove the lines defining `screen/auto_scaling` and `screen/scale_factor` within it.

**Comment by dackdel** [comment]
![Screenshot from 2019-11-26 19-52-01](https://user-images.githubusercontent.com/380951/69641507-566f0580-1086-11ea-95c1-e72eb30c1c70.png)
so installed the app. then deleted the lines. and launched. still looks like this. its bit better than what it was but still different aspects of the ui is differently sized.

**Comment by eneshecan** [comment]
I had the same issues, with the #827 it should be fixed now!

**Comment by dackdel** [comment]
noob here tho. i cant compile it. will wait for the package.

**Comment by egraether** [comment]
We plan to release a maintenance build next week.
