### ISSUE TITLE
Crossbuilding using Meson results in " unknown target CPU ''armv7-a''  "

### ISSUE THREAD

**Issue by giellamoswhard** [CoatiSoftware/Sourcetrail#753]
I'm trying to run it on a project using meson and an old arm-linux-gnueabihf-g++ 4.7
using the compilationDB but when I start the indexing I get 

unknown target CPU ''armv7-a'' 

for all the files

**Comment by egraether** [comment]
Maybe you are using the wrong C or C++ standard. Please check your project settings.

**Comment by jefstath** [comment]
I generated a compilation database from a build of the ARM Linux kernel using **bear**. When I created the project from the database file I also got  **unknown target CPU "arm7-a"**  for every source file.

Each file appears to have been indexed but there is no data from any of these files in the project.

There does not appear to be any way of checking the architecture or C/C++ standard in the project editor when the project was created from a compilation database.

I am using Sourcetrail 2019.4.61 on Ubuntu 18.04.

**Comment by egraether** [comment]
Can you please check your `compile_commands.json` file and tell us the exact commandline parameter used to set the target to `arm7-a`.

You may need to override this setting by supplying a different target triple compatible to LLVM/Clang 8 at `Additional Compiler Flags` in the Project Settings.

**Comment by giellamoswhard** [comment]
Hi, the bulk of the options are..

> -std=c++11 -g  -march=armv7-a  -marm  -mthumb-interwork  -mfloat-abi=hard  -mfpu=neon 
> -mtune=cortex-a8  -fPIC  -pthread  -MD  -MQ

**Comment by jefstath** [comment]
I am compiling the Linux kernel for an i.MX6 (Cortex-A9) processor. In the environment I set up the following:
`$ export ARCH=arm
$ export CROSS_COMPILE=arm-linux-gnueabihf-
`

The build command is:
`$ bear make zImage modules dtbs`

In the `compile_commands.json` file the command for each file is:
`        "arguments": [
            "cc",
            "-c",
            "-Wp,-MD,drivers/block/.loop.o.d",
            "-nostdinc",
            "-isystem",
            "/usr/lib/gcc-cross/arm-linux-gnueabihf/7/include",
            "-I./arch/arm/include",
            "-I./arch/arm/include/generated/uapi",
            "-I./arch/arm/include/generated",
            "-I./include",
            "-I./arch/arm/include/uapi",
            "-I./include/uapi",
            "-I./include/generated/uapi",
            "-include",
            "./include/linux/kconfig.h",
            "-D__KERNEL__",
            "-mlittle-endian",
            "-Wall",
            "-Wundef",
            "-Wstrict-prototypes",
            "-Wno-trigraphs",
            "-fno-strict-aliasing",
            "-fno-common",
            "-Werror-implicit-function-declaration",
            "-Wno-format-security",
            "-std=gnu89",
            "-fno-PIE",
            "-fno-dwarf2-cfi-asm",
            "-fno-omit-frame-pointer",
            "-mapcs",
            "-mno-sched-prolog",
            "-fno-ipa-sra",
            "-mabi=aapcs-linux",
            "-mno-thumb-interwork",
            "-mfpu=vfp",
            "-marm",
            "-D__LINUX_ARM_ARCH__=7",
            "-march=armv7-a",
            "-msoft-float",
            "-Uarm",
            "-fno-delete-null-pointer-checks",
            "-Wno-frame-address",
            "-Wno-format-truncation",
            "-Wno-format-overflow",
            "-Wno-int-in-bool-context",
            "-O2",
            "--param=allow-store-data-races=0",
            "-DCC_HAVE_ASM_GOTO",
            "-Wframe-larger-than=2048",
            "-fstack-protector-strong",
            "-Wno-unused-but-set-variable",
            "-Wno-unused-const-variable",
            "-fno-omit-frame-pointer",
            "-fno-optimize-sibling-calls",
            "-fno-var-tracking-assignments",
            "-g",
            "-Wdeclaration-after-statement",
            "-Wno-pointer-sign",
            "-fno-strict-overflow",
            "-fno-stack-check",
            "-fconserve-stack",
            "-Werror=implicit-int",
            "-Werror=strict-prototypes",
            "-Werror=date-time",
            "-Werror=incompatible-pointer-types",
            "-DKBUILD_BASENAME=\"loop\"",
            "-DKBUILD_MODNAME=\"loop\"",
            "-o",
            "drivers/block/.tmp_loop.o",
            "drivers/block/loop.c"
        ],
`

**Comment by mlangkabel** [comment]
It looks like the flag `-march=armv7-a` is not recognized by the clang compiler. As a work-around you can try to specify another architecture using the `Additional Compiler Flags` box in your Sourcetrail project settings. All flags specified there will be __appended__ to the compile command used for indexing. So they will __override__ the value that is specified in your compileation database file. 

Please try to add `-march=arm` there.

**Comment by chrta** [comment]
> Please try to add `-march=arm` there.

Thank you for the hint. I am currently trying to use Sourcetrail in ubuntu for https://github.com/zephyrproject-rtos/zephyr. Adding just `-march=` did the trick for me. Still a lot of errors, but it seems to be usable.

**Comment by Jonkimi** [comment]
After install `clang` using apt and add `--target=arm` in `Additional Compiler Flags`, I solved my problem.
