### ISSUE TITLE
Communication channel for (wannabe) contributors

### ISSUE THREAD

**Issue by Baranowski** [CoatiSoftware/Sourcetrail#774]
First of all, thanks a lot for sharing 5 years' worth of your work! I'm still waiting to give it a try after I build dependencies without my CPU melting, but from the videos it looks exactly like what I needed.

Would you consider creating a mailing list and/or slack/IRC channel, etc. for people who want to contribute? Your project has a lot of forks already, and I saw some /r/rust people planning to write language support. Some way to communicate with all the interested developers would be great.

I signed up for your mailing list but it seems to be one-way. And the slack channel link doesn't work any more.

**Comment by egraether** [comment]
Hey, thanks for pointing out that the [Slack link](https://join.slack.com/t/sourcetrail/shared_invite/enQtNDc3MjcyOTk5MTc0LTNhOWZhZjAxZmU1NTM0YjhhMzRhZWE1NTQ2NjQyYjc1ODE2MzViOTliMWUwODBjN2NlMjkwMDc0MjAxMzJkY2E) expired. I just fixed it in the README. Please join, there is a channel for 'contributors' now.
