### ISSUE TITLE
MacOs - .dmg file is not mountable

### ISSUE THREAD

**Issue by chrisfxwolf** [CoatiSoftware/Sourcetrail#779]
Sourcetrail_2019_4_61_macOS_64bit.dmg is not mountable

![Sourcetrail_Error](https://user-images.githubusercontent.com/32544288/69330968-ddb61680-0c4b-11ea-98ac-1067f070a2f4.jpg)

My System:
Model Name:	Mac Pro
  Model Identifier:	MacPro5,1
  Processor Name:	Quad-Core Intel Xeon
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	32 GB
  Processor Interconnect Speed:	4.8 GT/s
  Boot ROM Version:	MP51.0089.B00
  SMC Version (system):	1.39f11
  SMC Version (processor tray):	1.39f11

**Comment by chrisfxwolf** [comment]
I was checking as well as .zip file. The zip is all right however didn't start, means the start window doesn't occur. Starting App from a terminal:

open /Applications/Sourcetrail_2019_4_61/Sourcetrail.app 

We see this error:
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Sourcetrail_2019_4_61/Sourcetrail.app.

**Comment by egraether** [comment]
The mounting issue is a duplicate of #619 

> We see this error:
> LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Sourcetrail_2019_4_61/Sourcetrail.app.

This can be caused by gatekeeper when the same application is available multiple times. Did you remove your old Sourcetrail version from `/Applications`?

**Comment by chrisfxwolf** [comment]
> The mounting issue is a duplicate of #619
> 
> > We see this error:
> > LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Sourcetrail_2019_4_61/Sourcetrail.app.
> 
> This can be caused by gatekeeper when the same application is available multiple times. Did you remove your old Sourcetrail version from `/Applications`?

Yes, I do completely. As you see from AppCleaner the all files will be deleted. Which've been done and installed again:

**Comment by chrisfxwolf** [comment]
Sorry, I was coincidentally closing this issue. Is still open.

**Comment by chrisfxwolf** [comment]
> The mounting issue is a duplicate of #619
> 
> > We see this error:
> > LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Sourcetrail_2019_4_61/Sourcetrail.app.
> 
> This can be caused by gatekeeper when the same application is available multiple times. Did you remove your old Sourcetrail version from `/Applications`?

Ok, I'll check and reporting here.

**Comment by phil-blain** [comment]
As I wrote in #619 :
@egraether Regarding the unmountable disk image: this is due to the fact that `hdiutil` defaults to the new APFS file system on High Sierra and higher. You need to use `-fs HFS+` to create the disk image in HFS+ format that will be readable on Sierra and lower.

Reference:
https://davidnelson.net/2017/09/high-sierra-dmg/

**Comment by egraether** [comment]
Is this still an issue? Please try our [latest release](https://github.com/CoatiSoftware/Sourcetrail/releases)

**Comment by chrisfxwolf** [comment]
I was to give up this project on the Apple Computers. Not that mounting problem, but my pissed off about macOS. Hence, I was back to Linux, all is normal. I'm closing this discussion as a done without the solution from my side.
