### ISSUE TITLE
Chocolatey Package

### ISSUE THREAD

**Issue by digitalcoyote** [CoatiSoftware/Sourcetrail#780]
I just learned about this software, and when I ran `choco install sourcetrail -y` I got an error. I've made a few [Chocolatey packages](https://github.com/digitalcoyote/chocolatey-packages) and I'd love to add one for the project. If you don't know, [Chocolatey](https://chocolatey.org/) is a Windows Package Manager.

1.  If the maintainers of this would prefer to host their own CI to update the package, I can create the package, add it to my CI and assist integration of the package's updater. (My AU repo is hooked up to AppVeyor and checks github for updates and alters the chocolatey scripts to point to new versions) before publishing new packages.
2. If you would prefer to have some control over the package (so you can manually push updates or delist dangerous versions), I can add maintainer(s) chocolatey account(s) to the package after it's published. This adds some credibility to the installer as well.

I'll try to start on the install scripts when I get some time. Let me know if either of the above apply.

**Comment by mlangkabel** [comment]
Having a choco package sounds nice! I will read up on the topic and let you know.

**Comment by mlangkabel** [comment]
Feel free to create the choco package. If you want, you can add it to your CI, but what triggers the update?

**Comment by digitalcoyote** [comment]
It checks the Releases page twice a day and compares that version to the version currently available on Chocolatey.

**Comment by digitalcoyote** [comment]
https://chocolatey.org/packages/sourcetrail/2019.4.61 awaiting moderation. I can grant management rights to the package (delist vulnerable versions, push new versions, add/remove maintainers, etc) to an official account for CoatiSoftware if you would like to create one. 

Moderation for new packages seems to take a while. The CI will check 2x daily for new versions (which will need to go through moderation as well). Moderators are volunteers, so it may take a bit for this to be officially available. I'll try to get a PR for the readme here with install instructions (from Chocolatey) once it goes live.

**Comment by mlangkabel** [comment]
Sounds great! Thank you for working on this! I just took a look at the package on choco with the link you provided and have one remark: Can you please change it from "SourceTrail" to "Sourcetrail", just to be consistent? ;)

**Comment by digitalcoyote** [comment]
I pushed an update to the package that should correct that title.

**Comment by mlangkabel** [comment]
Ok, we have set up an account on chocolatey. It is "CoatiSoftware". You can add it to the package if you want :)

**Comment by mlangkabel** [comment]
It looks like everything is working now. And thank you @digitalcoyote for updating to the 2019.4.102 release! I've changed the Readme to point to the choco package :)
