### ISSUE TITLE
JavaIndexer not found in JVM environment

### ISSUE THREAD

**Issue by schoeneicher** [CoatiSoftware/Sourcetrail#787]
When indexing a Java project (here the included javaparser) I get this error in the log:
`JavaEnvironment.cpp:149 JavaEnvironment::getJavaClass() | ERROR: class com/sourcetrail/JavaIndexer not found in JVM environment`

and no Java details in the result:
```
	138 files
	34937 lines of code

	138 symbols
	0 references

	0 errors (0 fatal)
```
and this in the **LET'S GET STARTED!** section:
`[symbol not found (com.github.javaparser.ast.body.ClassOrInterfaceDeclaration)] // <- start here!
`

I am running Sourcetrail 64 bit, version 2019.4.61, on Windows 10, with Java 6, installed with Sourcetrail_2019_4_61_Windows_64bit_Installer.zip.

Thanks!

**Comment by schoeneicher** [comment]
It works using Java 8.

**Comment by egraether** [comment]
This should be mentioned in the Sourcetrail documentation as well as in the Preferences window.

**Comment by mlangkabel** [comment]
I just checked. This is already mentioned in the documentation and also in the help dialog for the "Java Path" option in Sourcetrail's preferences.
