### ISSUE TITLE
Java Maven not uses settings.xml

### ISSUE THREAD

**Issue by RuslanSafa** [CoatiSoftware/Sourcetrail#794]
To analyze my project, it is necessary to specify the settings.xml maven, there is no way to do this in the setup, but from the lack of a project it is not going to, there is accordingly no way to use the product.

**Comment by mlangkabel** [comment]
@RuslanSafa, thank you very much for bringing this up! 

It looks like we'd need to extens the project setup for maven projects with an optional path-picker for a settings.xml file. 

And if there is a path set here, the maven commads that Sourcetrail executes need to contain the `--settings path/to/settings.xml` argument.

**Comment by RuslanSafa** [comment]
@mlangkabel  Thank you for the product. I will wait for revision, I really want to use the product.

**Comment by mlangkabel** [comment]
Implemented with merge of pull request #847. This should be part of our next release.

**Comment by RuslanSafa** [comment]
Th's, I'll be waiting
