### ISSUE TITLE
Python indexing: too many CPU resources until the PC freezes

### ISSUE THREAD

**Issue by Odle98** [CoatiSoftware/Sourcetrail#795]
My configuration:

- OS: Ubuntu 18.04
- CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
- RAM: 8GB
- SDD 256GB

The problem: when I try to index files of my company Python project without Shallow indexing mode the CPU (and PC fans) rises to 100% until the PC freezes.

I can't provide the source code of the project but if there is any log file or traceback I can provide it.

If I run top while indexing:
![2](https://user-images.githubusercontent.com/17176752/69625442-dc6b5c00-1046-11ea-90bc-78f26f409046.png)

The indexing that starts the problem:
![1](https://user-images.githubusercontent.com/17176752/69625474-ebeaa500-1046-11ea-9104-3782b257fa2f.png)

Thanks in advance for any help :-)

**Comment by mlangkabel** [comment]
Hm, how many indexer threads are you using?

**Comment by Odle98** [comment]
> Hm, how many indexer threads are you using?

sincerely, I don't even know. I think the default ones because I haven't edited such settings

**Comment by andronov-alexey** [comment]
Had similar issue: during indexing my laptop CPU was throttled and CPU speed was dropping from ~3Ghz to ~0.7Ghz
Solved it by setting 6 cores instead of 7 in sourcetrail settings (I have an 8 core CPU)

**Comment by mlangkabel** [comment]
Yes, that's exactly why we made this option available ;)
