### ISSUE TITLE
Remember graph zoom level on close and restart

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/Sourcetrail#801]
The current graph zoom level should be stored to the ApplicationSettings, but not displayed in the preferences dialog.

Implementation suggestion:
- in `ApplicationSettings` add getter and setter for zoom level
- in `QtGraphicsView` store and load this new setting

**Comment by diohabara** [comment]
@egraether Hi, I'd like to help this issue.
Can you assign me?

**Comment by egraether** [comment]
Sure. Let me know if you have questions!

**Comment by mlangkabel** [comment]
Implemented via merge of pull request #1099. Thanks @miltolstoy!

**Comment by miltolstoy** [comment]
My pleasure.
