### ISSUE TITLE
Store last filepicker location in application settings

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/Sourcetrail#802]
After restarting Sourcetrail this location shall be used as the first default when opening a file picker dialog.

**Comment by Alvoda** [comment]
Is this still an issue?
If yes, could you be more specific about which file picker dialog is meant?
I assume it is "Open Project" on the splash screen?
Which class is used to store such things?

**Comment by mlangkabel** [comment]
Thank you for asking, yes, this is still an issue. 

The class that implements this dialog is calles `QtFileDialog`. It is wrapping the `QFileDialog` and adds some more functionality. I think the methods that need to be changed are:
```
getFileNamesAndDirectories
getExistingDirectory
getOpenFileName
showSaveFileDialog
```

The filepicker location sould be stored in the `ApplicationSettings.xml` file which is managed by the `ApplicationSettings` class.

**Comment by Alvoda** [comment]
Thank you for your reply. The code is mostly uncommented, that makes it difficult to dive in.
I have a (very) small patch that does the job - i think.

So whenever you open a project the user/lastUsedProjectsPath gets updated and will be the default path for the next "open project" - even after restart.

I dont know if it makes sense to change every file picker dialog that way. Especcially of you create a new project its probably annoying and not very helpful.

**Comment by miltolstoy** [comment]
Hi.
As I can see, Alvoda is absent for several months.
Please assign this issue to me.
