### ISSUE TITLE
How to change the Compiler Standard for a source group

### ISSUE THREAD

**Issue by PhilipOakley** [CoatiSoftware/Sourcetrail#803]
After some initial phaff (#790), I am now down to 4 errors, all of which are around two `static inline int` definitions.

Unfortunately I had selected the C90 standard when initially selecting the souce group as the project is nominally C89. However the `static inline` is C99 and not picked up by Clang.

I cannot find the method for changing a Source Group's compiler or standard, which are set as a one off on creation of the group.

How to change a source group's standard version (C90 to C99)?

**Comment by egraether** [comment]
You can change the standard within the `Edit Project` dialog: 
<img width="1012" alt="Screenshot 2019-11-26 at 22 52 19" src="https://user-images.githubusercontent.com/201867/69675745-a0b0b080-109f-11ea-8ed4-884b22cdc6b2.png">

Does this not show up for you? Which Source Group Type did you choose?

**Comment by PhilipOakley** [comment]
Hi,
It's from the compilation database group, but I'm fairly sure there was a step where I entered the standards before the database loaded. 

Now all I see for editing is:

![image](https://user-images.githubusercontent.com/914343/69678782-6e528380-109e-11ea-8ed2-40620908f740.png)

It looks like there's a 'gap' for between the two styles of edit.

**Comment by egraether** [comment]
In that case the standard present in the compile commands is used. To use a different standard please add `-std=c89` to `Additional Compiler Flags`

**Comment by PhilipOakley** [comment]
Magic used the `-std=c99` (need to accept `inline`) and it's now fully indexed with 

      0 errors (0 fatal)

So all good. I'm adding a couple more little usability issues #804 #805 just to capture them.

**Comment by mlangkabel** [comment]
To explain what happens here: The `Additional Compiler Flags` get appended to the compiler flags of each compile command of the compilation database. And the Clang compiler that is used by Sourcetrail's Cxx language analysis only uses the **last** value for each provided flag.

**Comment by PhilipOakley** [comment]
> The `Additional Compiler Flags` get appended to the compiler flags of each compile command of the compilation database. And the Clang compiler that is used by Sourcetrail's Cxx language analysis only uses the **last** value for each provided flag.

Thanks Eberhard, 
I think the soft issue I was noting was that I was expecting that the 'edit project' dialog would show the current selection somewhere in the dialog box, and second that the current selection must be recorded _somewhere_ but I couldn't find it.  (i.e. the .srctrlprj file doesn't show it in the xml text). 

And ultimately it will need a note in the documentation to remind the users that they may need to do that - not sure of the right place to copy your explanation to... (so as to reduce the support workload ;-)
