### ISSUE TITLE
Add clang-format file

### ISSUE THREAD

**Issue by andronov-alexey** [CoatiSoftware/Sourcetrail#812]
I'd very much like to use auto-formatting for the repo
If somebody already have one - please share otherwise I'll add it on coming holidays :)
PS: If I'm not wrong @mlangkabel mentioned somewhere using clang-format file :)

**Comment by egraether** [comment]
There already is one: `script/.clang-format`. I don't understand why it doesn't have a file name. Is this convention? Should it be in the top-level directory?

**Comment by andronov-alexey** [comment]
it should be in top-level folder for IDE's to automatically catch it up :)
I suggest we move it there then
Yeah, filename starting with dot is a convention (same as `.git`)
