### ISSUE TITLE
Add option "Close Tabs to the Right" to right-click context menu of tabs

### ISSUE THREAD

**Issue by mlangkabel** [CoatiSoftware/Sourcetrail#822]
Implementation suggestion:
* override `void contextMenuEvent(QContextMenuEvent* event)` in `QtTabsBar`
* Instantiate `QtContextMenu` and add this action to it (see `QtGraphicsView` for example)
* when action is triggered emit a signal, e.g. `closeTabsToRight(Id tabId)`.
* catch that signal in `QtTabsView` and handle logic there

**Comment by kalashshah11** [comment]
I am interested to work on the project for some time. Can you provide me with details on how can I start with? I am a 2nd-year undergrad.

**Comment by egraether** [comment]
@kalashshah11 I updated the description above to give some pointers.

**Comment by kalashshah11** [comment]
@egraether Thanks for updating.Would complete it as soon as possible.

**Comment by kalashshah11** [comment]
@egraether I am getting an error of CMake Error at "D:/......." Could NOT find Boost (missing: Boost_INCLUDE_DIR system program_options filesystem date_time) (Required is at least version "1.67")
and am not being able to load the project

**Comment by mlangkabel** [comment]
Please read the [Building the Bare Minimum](https://github.com/CoatiSoftware/Sourcetrail#building-the-bare-minimum) section of our readme and install the required software.

**Comment by kalashshah11** [comment]
After following the ReadME file, still, I am getting the same errors

**Comment by mlangkabel** [comment]
Are you working on Windows? Maybe you need to define a CMake Cache Entry called `BOOST_ROOT` (hm, maybe the casing was different, but give it a try) pointing to the directory that contains the "boost" folder, e.g., `C:\Program Files\boost\boost_1_68_0`. If that doesn't help, just google for CMake find boost and see if anything that comes up helps.

**Comment by Alvoda** [comment]
Hey @kalashshah11 are you still working on this feature?
I think i am already close to a solution.

**Comment by Alvoda** [comment]
Hm, i guess im an impatient one... 
Just created a pull request (#875) for this one...

**Comment by mlangkabel** [comment]
It has been 22 days since the last activity on this issue, so I think its fine :)

**Comment by egraether** [comment]
Implemented with 2422e09
