### ISSUE TITLE
C++ superclass method calls not recognized

### ISSUE THREAD

**Issue by nemesis5** [CoatiSoftware/Sourcetrail#828]
# Versions
**Platform version:** Windows 10 Pro Update 1903
**Sourcetrail version:** 2019.4.61 - 64bit Windows, database version 25

# Description of the problem
In C++ there is no `super` keyword, because C++ supports multiple inheritance and such a keyword would be ambiguous therefore.

If you need to e.g. extend a method of one of your super classes, you normally override the method, do what ever you need for your extension and call method of your super class.

Calls to methods of super classes are not recognized by sourcetrail. 
Calls to methods of any super class (works also to methods of super classes of your direct super classes) should be displayed in the call graphs to have a more complete overview of what is happening.

# Steps to reproduce the problem:

1. Save the following code to a .cpp file and create a new sourcetrail project which indexes the file: 
	```cpp
	#include <string>
	#include <stdio.h>


	class AbstractSpaceship
	{
	protected:
		AbstractSpaceship(){};
		
		std::string name;
		
	public:
		virtual ~AbstractSpaceship(){};

		virtual void prepareForWarp()
		{
			printf("Prepare for warp on %s\n", name.c_str());
			
			activateAlarm();
			loadWarpCoils();
			giveInstructionToAccelerate();
		};

		virtual void loadWarpCoils()
		{
			printf("Basic warp coil loading procedure started...\n");
		}

		virtual void activateAlarm() = 0; 
		virtual void giveInstructionToAccelerate() = 0; 
	};


	class EnterpriseNx01 : public AbstractSpaceship
	{
	public:
		EnterpriseNx01()
		{
			name = "Enterprise NX-01";
		}
		virtual ~EnterpriseNx01() {}
		
	public:
		virtual void loadWarpCoils()
		{	
			// Overrides AbstractSpaceship::loadWarpCoils() and has to extend it
			AbstractSpaceship::loadWarpCoils();
			
			printf("Additional warp coil loading procedures for old space ship versions\n");
		}
		
		virtual void activateAlarm()
		{
			printf("Quite old beeping alarm\n");
		}
		virtual void giveInstructionToAccelerate()
		{
			printf("Archer: *Saying-something--cannot-remember*\n");
		}
	};


	class EnterpriseNcc1701d : public AbstractSpaceship
	{
	public:
		EnterpriseNcc1701d() 
		{
			name = "Enterprise NCC-1701-D";
		}
		virtual ~EnterpriseNcc1701d() {}
		
	public:
		virtual void activateAlarm()
		{
			printf("No alarm needed any more\n");
		}
		virtual void giveInstructionToAccelerate()
		{
			printf("Picard: \"Energie!\"\n");
		}
	};


	void test_superclasscalls()
	{
		EnterpriseNx01 		oldSpaceship = EnterpriseNx01();
		EnterpriseNcc1701d 	newSpaceship = EnterpriseNcc1701d();
		
		printf("=============================================\n");
		oldSpaceship.prepareForWarp();
		printf("\n");
		
		printf("=============================================\n");
		newSpaceship.prepareForWarp();
		printf("\n");
	}
	```
2. After indexing chosse in the sourcetrail graph the method `EnterpriseNx01::loadWarpCoils()` which extends the same method of the superclass by adding additional functionality.
3. Click "show callee graph"
4. --> Issue --> There is no call shown. Instead of showing no call, it should display a call arrow to `AbstractSpaceship::loadWarpCoils()` (can be seen in the source code on the right side). On hovering over the `AbstractSpaceship::loadWarpCoils()` code in the right side source window there is no effect, like it was not indexed. 
![2019-12-04 15_52_50-Sourcetrail - test_superclasscalls srctrlprj](https://user-images.githubusercontent.com/10476509/70152957-656d3d80-16ae-11ea-8815-6589e21a38f7.png)

**Comment by mlangkabel** [comment]
As far as I know this should be working. If not, this would be a bug. 

But I see that you have **1 fatal error**. That may very likely be the reason for missing edges in the graph. Can you please fix the fatal error and re-run the indexing?

**Comment by nemesis5** [comment]
I fixed the fatal errors by including the headers for stl string and rerun the steps to reproduce. Now the needed call is shown in the graph.
Thank you for the help and sorry for not solving all fatal issues before. For me it was not very intuitive that the fatal error showed "yes" in the "Indexed" column of the status message. This is why I thought this has no influence on the result.

Here is the new call graph after inserting the right include directives into the project settings:
![After-fixing-include-directives](https://user-images.githubusercontent.com/10476509/70215370-a1031880-173d-11ea-9d9e-da07d5d6baf0.png)

Am I right in the assumption that I only have to fix fatal errors in indexed files (see message filter settings in the screenshot) to be sure to have the full possible graph/index?

**Comment by mlangkabel** [comment]
Thanks for the update. Yes, we recommend to fix all fatal errors because they can have a big impact on the graph that is not quite obvious when browsing.
Fixing normal errors is optional. Of course it the error states that some type is unknown, you won't get a usage edge of that specific type at that specific location. But the effect is very local. For example, if you have normal errors in non-indexed files, you can usually ignore them completely.
