### ISSUE TITLE
Show non-dependencies?

### ISSUE THREAD

**Issue by jankap** [CoatiSoftware/Sourcetrail#830]
This might not be the main goal of SourceTrail (which is awesome), but do you think it makes sense to visualize also non-dependencies, i.E. not connected graphs?
This could be extremely helpful to search for cases where a specific file or symbol is *not* used by another file.
With that, for example I could find out that
- a Logger module is not used by another module
- a configuration header is not included by 1 file (but probably by 100 other files?)
- The expected call to a function x from another source does not exist 
- and so on.

As a workaround, is there a way to visualize *all* files with their connection to other files (like an overlay of all references of each file)? Highlighting some connections could also find the mentioned issues above.

Thanks,
Jan

**Comment by egraether** [comment]
This could be part of a more extensive query syntax (#250). Let's continue there.
