### ISSUE TITLE
[bug/feature-request] Sourcetrail does not find make_shared constructor calls.

### ISSUE THREAD

**Issue by catskul** [CoatiSoftware/Sourcetrail#840]
Many constructors are called from within std::make_shared, make_unique. 

It would be extremely helpful to find these.

**Comment by egraether** [comment]
Sourcetrail should be able to find those constructor calls, but only if you also index the std library within your project.

**Comment by catskul** [comment]
Oh, interesting!

Will investigate today.

**Comment by egraether** [comment]
No reply in 3 months. Closing now.
