### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [CoatiSoftware/Sourcetrail#848]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [QtMainWindow](https://github.com/CoatiSoftware/Sourcetrail/blob/21f2625d9e0a2526ce5b710587204917939d6451/src/lib_gui/qt/window/QtMainWindow.cpp#L154 "Destructor for QtMainWindow")
- [TicTacToe::Reset](https://github.com/CoatiSoftware/Sourcetrail/blob/21f2625d9e0a2526ce5b710587204917939d6451/bin/app/user/projects/tictactoe_cpp/src/tictactoe.cpp#L57 "TicTacToe::Reset function")

**Comment by mlangkabel** [comment]
I'm frequently amazed by the quality of our code base ;) 

@elfring: You are absolutely right. 

`QtMainWindow::m_recentProjectAction` should be a `std::vector<QAction*>` so the destructor wouldn't have to do anything about it. I believe the individual actions will be deleted by Qt as they are created with `QtMainWindow` as parent.

However, I think that TicTacToe::Reset is written like this by intention as it is our example project that gets shipped with Sourcetrail pre-indexed. And the example should just illustrate what Sourcetrail does in such a case.

**Comment by elfring** [comment]
Should all affected source code places demonstrate better programming practices?

**Comment by mlangkabel** [comment]
"Better programming practives" sounds nice. What do you have in mind?

**Comment by elfring** [comment]
I suggest to [look for further update candidates with the help of a development tool like “clang-tidy”](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks") besides taking possible source code adjustments into account which you mentioned.

**Comment by mlangkabel** [comment]
Improving the quality of the code base sounds great. If you want to work on this, please go ahead :)

**Comment by elfring** [comment]
Was an [update candidate](https://github.com/CoatiSoftware/Sourcetrail/blob/21f2625d9e0a2526ce5b710587204917939d6451/bin/app/user/projects/tictactoe_cpp/src/tictactoe.cpp#L57 "Update candidate: TicTacToe::Reset()") left over?

**Comment by egraether** [comment]
> Was an [update candidate](https://github.com/CoatiSoftware/Sourcetrail/blob/21f2625d9e0a2526ce5b710587204917939d6451/bin/app/user/projects/tictactoe_cpp/src/tictactoe.cpp#L57) left over?

That's just sample code
