### ISSUE TITLE
Sourcetrail was unable to locate Maven on this machine

### ISSUE THREAD

**Issue by miaojingyuan** [CoatiSoftware/Sourcetrail#855]
hi,i create a new java project from maven ,but i get this error.i am sure that i set the maven path correctlly. and then,i look the sorce code,and find the applicatio get the maven path through excute the command "which maven".i execute the command and get the correct result "/Library/apache-maven-3.3.9/bin/mvn". so now ,i do not know how to do.can you guys help me?

**Comment by mlangkabel** [comment]
Hm, maybe your Sourcetrail is running in a different console environment where maven is not known?

**Comment by egraether** [comment]
Are you on macOS? Try launching Sourcetrail directly from your Terminal, instead of using the application launcher.

**Comment by ScnuWang** [comment]
@miaojingyuan I found the solution, you can manually set maven path by yourself:
 **_toolbar---->Edit ---> perferences----> maven path_**

**Comment by daymade** [comment]
@ScnuWang  On Version 2019.4.102 I cannot find the option you mentioned.


![image](https://user-images.githubusercontent.com/4291901/71575498-205eee80-2b28-11ea-8fe5-7e309ef07d8d.png)

**Comment by mlangkabel** [comment]
I think for macOS it is 
__toolbar---->Sourcetrail ---> perferences----> maven path__

**Comment by daymade** [comment]
This is not working, that's the issue talking about.

________________________________

**Comment by daymade** [comment]
I have set the maven path to `/usr/local/Cellar/maven/3.6.3/libexec/bin`, but got this error too :

> Sourcetrail was unable to locate Maven on this machine. Please make sure to provide the correct Maven Path in the preferences.

```shell
~ ls /usr/local/Cellar/maven/3.6.3/libexec/bin/mvn
/usr/local/Cellar/maven/3.6.3/libexec/bin/mvn
```

**Comment by mlangkabel** [comment]
Please try to set the path to `/usr/local/Cellar/maven/3.6.3/libexec/bin/mvn`.

**Comment by daymade** [comment]
@mlangkabel it works, thanks

**Comment by miaojingyuan** [comment]
@mlangkabel  
set the path to /usr/local/Cellar/maven/3.6.3/libexec/bin/mvn
it works for me too,thanks.All of you guys who meet the same prombem could try this way.
