### ISSUE TITLE
ubuntu16.04 symbol lookup error

### ISSUE THREAD

**Issue by fridayfang** [CoatiSoftware/Sourcetrail#859]
Hi,
when I start the Sourcetrail after installation , I get a symbel lookup error.
The information is:
>
/opt/sourcetrail/Sourcetrail: symbol lookup error: /opt/sourcetrail/lib/libGL.so.1: undefined symbol: _glapi_tls_Current

what shold I do to solve this problem?

**Comment by egraether** [comment]
Which Sourcetrail version did you use?

This is likely a legacy Nvidia driver issue, where our build is not properly linked against `libglvnd` (see [1](https://github.com/guibou/nixGL/issues/14), [2](https://bugzilla.redhat.com/show_bug.cgi?id=1440124), [3](https://www.linuxquestions.org/questions/slackware-14/optirun-fails-to-run-glxgears-reporting-undefined-symbol-_glapi_tls_current-4175653832/))

**Comment by fridayfang** [comment]
thanks for your help!
I was so busy recently that I didn't reply in time. Please forgive my rudeness.

I install sourceTrail using the release version `Sourcetrail 2019.4.102`. And when I run `nm -D libGL.so.1 | grep _glapi_tls_Current` in `/opt/sourcetrail/lib`, the terminal display nothing. So no such symbol in libGL.so.1 ??

I try another release version `Sourcetrail 2019.4.61` and it works.  And when I run `nm -D libGL.so.1 | grep _glapi_tls_Current` in `/opt/sourcetrail/lib`, the terminal still display nothing.  But this version alreay has solved my prolem.

thanks for your help again.

**Comment by egraether** [comment]
Can you please test if you have the same issue with [Sourcetrail 2019.4.61](https://github.com/CoatiSoftware/Sourcetrail/releases/tag/2019.4.61)?

**Comment by fridayfang** [comment]
The release version `Sourcetrail 2019.4.61` works with no problems in my ubuntu 16.04

**Comment by egraether** [comment]
Another user wrote via e-mail:
> I was able to fix this undefined symbol by updating my NVidia driver and libglvnd

**Comment by ScottFries** [comment]
Another data point @egraether: on my end I run in to this issue with Sourcetrail 2019.4.102, but not the older Sourcetrail 2019.4.61 you mention above.

**Comment by egraether** [comment]
I worked on creating a `.AppImage` package for Linux (#945). It hopefully solves this issue, which is likely caused by our non-standard way of packaging. Can you please test the beta release of the `.AppImage` package [downloadable from here](https://github.com/CoatiSoftware/Sourcetrail/releases/tag/2020.1.131)?
