### ISSUE TITLE
Suggestion : focus on source code itself something like Source Insight, not the graphics

### ISSUE THREAD

**Issue by Passw** [CoatiSoftware/Sourcetrail#867]
First, I would like to thank you for the efforts of creating this good quality tool.

After some basic usage, found that while using `Sourcetrail` the programmer's attention will be attracted by the `graphics`, but do not focus on the source code itself. This will need extra effort of the programmer to map the `graphics` to the `original source code` in mind. But on the other hand `Source Insight` always focus on the `source code`. `Source Insight` itself has some weakness compared to `Sourcetrail`, eg, do not have compilation database support.

Suggestion : to move source code in the main window and focus on source code, the `graphics` as assistant just like `Source Insight`

**Comment by mlangkabel** [comment]
Thanks for sharing your thoughts!

However, we built Sourcetrail not just to make a clone of Source Insight with compilation database support. The concept of Sourcetrail revolves around having this interactive connection between graph and code. What does that mean? If you click something in the graph, the code will show you the definition of the clicked symbol or reference. If you click something in the code, the graph will adjust respectively. If you don't want to click (and change) anything, you can just hover symbols in the graph or in the code and the other view will highlight the hovered item respectively.

When using Sourcetrail I am constantly shifting my attention between graph and code. Sometimes it is easier to navigate in the graph, 10 seconds later I see something in the code and continue navigating there.

Sourcetrail provides as much context as possible. That is what Sourcetrail is all about. And that won't change. Of course, if anyone feels that the graph is distracting, you can always close the graph window ;)
