### ISSUE TITLE
Symlink to data is missing

### ISSUE THREAD

**Issue by Alvoda** [CoatiSoftware/Sourcetrail#870]
Hi everyone,

i just cloned the repo, installed dependecies und built the software.
In `build/Release/app` i had no symlink to `Sourcetrail/bin/app/data/`

I created it manually and now things are fine.

**Comment by mlangkabel** [comment]
Thanks for reporting. What platform are you working on?

**Comment by Alvoda** [comment]
Yes i should have added that. I'm on Ubuntu 19.10, 64 Bit. 
I will look into the CMakefiles. Maybe i can fix it...

**Comment by mlangkabel** [comment]
For Windows I recently changed the main CMake file to set up the symlinks. If you manage to do the same for Linux, I would be happy to accept your pull request :)

**Comment by Alvoda** [comment]
This is just too strange...

In build/Release i run `cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_CXX_LANGUAGE_PACKAGE=ON  ../..`

cmake outputs:
[cmake_output.txt](https://github.com/CoatiSoftware/Sourcetrail/files/4009455/cmake_output.txt)

Now the symlinks are created!?

Then i clear the build Dir with `rm -rf *`, run the exact cmake command again an get this output:
[cmake_output_2.txt](https://github.com/CoatiSoftware/Sourcetrail/files/4009471/cmake_output_2.txt)

Now only the symlink to `bin/app/user` is created. What the hell? Could it be my system?

**Comment by mlangkabel** [comment]
Maybe you created the first symlink in a way that `rm -rf *` also removed the target directory of the link. From the cmake output that you uploaded it looks like that's the case.

**Comment by Alvoda** [comment]
No, it was something else. execute_process() in CMakeLists.txt seems to create a new child-process for every COMMAND:

> If a sequential execution of multiple commands is required, use multiple execute_process() calls with a single COMMAND argument.

[source](https://cmake.org/cmake/help/v3.13/command/execute_process.html)

And then:

> create_symlink OLD NEW
    Create a symbolic link NEW naming OLD.
Note: Path to where NEW symbolic link will be created has to exist beforehand. 

That means **sometimes** the system tried to link before the `/app`-Directory was created.
I just splitted the execute_process-Commands into two calls of execute_process. That fixed it. 
Ill try to upload the patch, as soon as i find out how that works - still new to github;-)

**Comment by mlangkabel** [comment]
Fixed with Sourcetrail 2020.1.62 by merging pull request #872. Thank you @Alvoda!
