### ISSUE TITLE
heavy CPU used in python indexing

### ISSUE THREAD

**Issue by yutiansut** [CoatiSoftware/Sourcetrail#871]
![image](https://user-images.githubusercontent.com/11537812/71565600-2bdff480-2aeb-11ea-9692-d38f101ddd4c.png)

**Comment by mlangkabel** [comment]
You didn't state any issue explicitly, but I would guess, that you don't think that it is a good idea for Sourcetrail to use all of your cores?

If that's the case you can reduce the number of used cores in your Sourcetrail preferences.

**Comment by yutiansut** [comment]
> You didn't state any issue explicitly, but I would guess, that you don't think that it is a good idea for Sourcetrail to use all of your cores?
> 
> If that's the case you can reduce the number of used cores in your Sourcetrail preferences.

allright  thanks-～
