### ISSUE TITLE
Every Maven project I try indexes 0 files

### ISSUE THREAD

**Issue by Josemartins-ptc** [CoatiSoftware/Sourcetrail#885]
Maven settings is pointing to the correct file.
Maven is working properly.
Java installed on the machine is OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04).

tried several different projects, and the result is always the same. 0 indexed files when choosing maven project.

On the other hand, creating the project as an empty java project , partially works, obviously with many errors, as it does not find dependencies.

Any hint ?

Thanks in advance.

**Comment by mlangkabel** [comment]
Hi @Josemartins-ptc, thanks for reaching out. What happens if you go to the project settings of your maven based Sourcetrail project and click the "show source files" button?

**Comment by Josemartins-ptc** [comment]
It shows 0 files :(

**Comment by mlangkabel** [comment]
Ok, what happens if you execute `mvn help:effective-pom` from your console? Sourcetrail runs that command to generate a pom and read all source directories from there.

Are you working on a confidential project? Or can you share the generated effective pom? You can generate a file by adding the `-Doutput="somefile"` flag.

Also what does the Sourcetrail log file say? Sourcetrail should write something to the file when you clicj the "show source files" button.

**Comment by Josemartins-ptc** [comment]
Unfortunately I can not share Pom file as there are some confidential libs and plugins, but help:effective-pom works perfectly, and that's why I do not understand why it is not working...

--- maven-help-plugin:3.2.0:effective-pom (default-cli)
....tree of dependencies (its a spring boot project)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.215 s
[INFO] Finished at: 2020-01-07T10:18:31Z
[INFO] ------------------------------------------------------------------------

**Comment by Josemartins-ptc** [comment]
thsi is what I have on teh Status section :

Preparing Project: Maven Generating Source Files
Preparing Project: Maven Exporting Dependencies
Preparing Project: Maven Fetching Source Directories
Preparing Indexing
Preparing Indexing: Setting up Indexers
Preparing Project: Gathering Root Directories
Starting Indexing: 0 source files
Finish Indexing: Optimizing database
Finished indexing: 0/0 source files indexed; 00:00:00:141; 0 errors

NO Errors

**Comment by mlangkabel** [comment]
Hm, probably Sourcetrail managed to execute the maven command successfully but managed to parse the generated pom. Can you take a look at the effective pom and check if it contains the following structure:
```xml
<project>
  ...
  <build>
    ...
    <directory>
...
```
or
```xml
<projects>
  <project>
    ...
    <build>
      ...
      <directory>
...
```

**Comment by Josemartins-ptc** [comment]
ok I found this in the log file.

ERROR: Maven effective-pom didn't generate an output file: /home/josemartins/Documents/sourcetrails/ps2/sourcetrail_dependencies/e78b88d2-3ecd-47b0-926c-e6188eecc1db/maven/effective-pom.xml

**Comment by mlangkabel** [comment]
Would Sourcetrail have write permission to that directory?

**Comment by mlangkabel** [comment]
Sourcetrail executes `mvn help:effective-pom -Doutput="/home/josemartins/Documents/sourcetrails/ps2/sourcetrail_dependencies/e78b88d2-3ecd-47b0-926c-e6188eecc1db/maven/effective-pom.xml"` on your machine.

**Comment by Josemartins-ptc** [comment]
Ok..then siomething is wrong. Just to make sure I created a new folder with 777 and created a new project.
the only files there are

teste.srctrlbm 
teste.srctrldb
teste.srctrldb_tmp
teste.srctrlprj

there is a tmp jornal created during indexing for a fraction of second.

nothing else.

**Comment by mlangkabel** [comment]
There should also be a `sourcetrail_dependencies` folder in that directory. But maybe Sourcetrail doesn't even get to use that folder because the maven step fails.
What happens if you run `mvn help:effective-pom -Doutput="/home/josemartins/Documents/sourcetrails/ps2/sourcetrail_dependencies/e78b88d2-3ecd-47b0-926c-e6188eecc1db/maven/effective-pom.xml"` from your console? Does it create the output file?

**Comment by Josemartins-ptc** [comment]
If I do it manualy from the java project folder, it does run and creates the effectivepom file.

**Comment by Josemartins-ptc** [comment]
Solved. Thanks for your support.

**Comment by mlangkabel** [comment]
@Josemartins-ptc, great to hear that! Can you tell us how you solved the issue?

**Comment by Josemartins-ptc** [comment]
Hi @mlangkabel , to be honest I was given a new computer at office. Reinstalled all my dev tools and prepared all environments I need to work, then I decided to try Sourcetrail again...But this time I downloaded the linux Appimage instead of the tar.gz...executed it, and it run out of the box, without any problem. So no interesting magic here :)

I'm now in the process of exploring how it can help me to speedup mapping and following flows of some huge codebases.

If it could only handle lombok...without the need to delombok, everything, would be easier. :)
But so far I'm quite happy with it.

I will also look at your code base, when I have some free time, to get a better understanding of how it works.

many thanks to everyone involved on a great Idea and a great product.

**Comment by mlangkabel** [comment]
Thanks for getting back to this. I'm really glad that we now have the Appimage and that it seems to be working fine :)

For the lombok support: I have been looking into if a couple of years ago and we would have been required to write and maintain a completely seperate indexer for that. But maybe the tools have improved by now. We will see once we look into it again!

**Comment by dmitryshm** [comment]
The same bug here but on Windows. I think it's the reason why sourcetrail isn't so popular. It simply refuses to work.
