### ISSUE TITLE
Find types qualified as pointers

### ISSUE THREAD

**Issue by l4l** [CoatiSoftware/Sourcetrail#89]
``` c
char a;
char *b;
```

This variables have same types :(

**Comment by egraether** [comment]
Yes it is intended, so that when you look at the references of a type, you really see all references.

It would be possible to add pointer type as attribute though, so you can still search for it.

**Comment by l4l** [comment]
Yeah, that's much better

**Comment by egraether** [comment]
Hasn't come up again. Closing now.
