### ISSUE TITLE
Error:undefined symbol: _glapi_tls_Current

### ISSUE THREAD

**Issue by zg9uagfv** [CoatiSoftware/Sourcetrail#891]
ubuntu 18.04
NVIDIA-SMI 440.44       Driver Version: 440.44       CUDA Version: 10.2
Sourcetrail_2019_4_102_Linux_64bit.tar.gz

`dh@zg9uagfv:/opt/sourcetrail$ ./Sourcetrail

./Sourcetrail: symbol lookup error: /opt/sourcetrail/lib/libGL.so.1: undefined symbol: _glapi_tls_Current
`
how to fix it？thanks a lot!

**Comment by egraether** [comment]
I think this is a duplicate of #869 and #859 

As some user pointed out at #859:

    I was able to fix this undefined symbol by updating my NVidia driver and libglvnd

Can you please try to install libglvnd:
```
sudo apt-get install libglvnd
```
Please let me know if that worked!

**Comment by zg9uagfv** [comment]
> I think this is a duplicate of #869 and #859
> 
> As some user pointed out at #859:
> 
> ```
> I was able to fix this undefined symbol by updating my NVidia driver and libglvnd
> ```
> 
> Can you please try to install libglvnd:
> 
> ```
> sudo apt-get install libglvnd
> ```
> 
> Please let me know if that worked!
It didn't work, got the same error.

`dh@zg9uagfv:/opt/sourcetrail$ sudo apt-get install -y libglvnd

Reading package lists... Done

Building dependency tree       

Reading state information... Done

E: Unable to locate package libglvnd

dh@zg9uagfv:/opt/sourcetrail$ sudo apt-get install -y libglvnd-dev

Reading package lists... Done

Building dependency tree       

Reading state information... Done

libglvnd-dev is already the newest version (1.0.0-2ubuntu2.3).

0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.

dh@zg9uagfv:/opt/sourcetrail$ ./Sourcetrail

./Sourcetrail: symbol lookup error: /opt/sourcetrail/lib/libGL.so.1: undefined symbol: 
_glapi_tls_Current`

**Comment by egraether** [comment]
Thanks for testing. You can use the last release meanwhile, which doesn't have this issue yet

**Comment by egraether** [comment]
I worked on creating a `.AppImage` package for Linux (#945). It hopefully solves this issue, which is likely caused by our non-standard way of packaging. Can you please test the beta release of the `.AppImage` package [downloadable from here](https://github.com/CoatiSoftware/Sourcetrail/releases/tag/2020.1.131)?

**Comment by zg9uagfv** [comment]
> I worked on creating a `.AppImage` package for Linux (#945). It hopefully solves this issue, which is likely caused by our non-standard way of packaging. Can you please test the beta release of the `.AppImage` package [downloadable from here](https://github.com/CoatiSoftware/Sourcetrail/releases/tag/2020.1.131)?

 it worked fine!

**Comment by pean1128** [comment]
> ubuntu 18.04
> NVIDIA-SMI 440.44 Driver Version: 440.44 CUDA Version: 10.2
> Sourcetrail_2019_4_102_Linux_64bit.tar.gz
> 
> `dh@zg9uagfv:/opt/sourcetrail$ ./Sourcetrail
> 
> ./Sourcetrail: symbol lookup error: /opt/sourcetrail/lib/libGL.so.1: undefined symbol: _glapi_tls_Current
> `
> how to fix it？thanks a lot!

I come across a similar problem  when I prepare to install Pangolin. I have solved this problem by reading https://forum.freecadweb.org/viewtopic.php?f=4&t=41985
