### ISSUE TITLE
Bug: SourceTrail Crash when project directory contains Non-Latin Character

### ISSUE THREAD

**Issue by xufangda** [CoatiSoftware/Sourcetrail#899]
The SourceTrail crash when I create a new project, and the project directory contains Non-Latin Character. When I click **"add Source Group"** Button, the sourcetrail will crash as shown below.

The directory is  C:/00_Temp_Fils_临时文件/Test
This kind of directory is very common in Non-English speaker User.

![image](https://user-images.githubusercontent.com/6506508/72809518-ae278880-3c53-11ea-8150-1c7dbb6d2ad7.png)

**Comment by mlangkabel** [comment]
Thanks for reporting. I just managed to reproduce it on Windows.

**Comment by mlangkabel** [comment]
It looks like boost just doesn't like those characters. With merge of pull request #901 the user will be prompted to enter a path with just latin characters, to prevent this situation from happening.
