### ISSUE TITLE
FilePath::isValid() broken on Linux/macOS

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/Sourcetrail#907]
Introduced by #901 
The method should be tested in FilePathTestSuite

**Comment by egraether** [comment]
@mlangkabel Can you please add tests for `FilePath::isValid`? I don't quite understand which should and shouldn't be invalid. Then I can look into fixing this for Linux/macOS.

**Comment by mlangkabel** [comment]
Added pull request #908 for the fix. @egraether: please test on Linux and Mac and modify if necessary before accepting.
