### ISSUE TITLE
Separate casts from var declarations

### ISSUE THREAD

**Issue by l4l** [CoatiSoftware/Sourcetrail#91]
For example:

``` c
unsigned a;

(unsigned)-1;
```

If I understand correctly I can't directly separate references of type unsigned by casts and declaration.

**Comment by egraether** [comment]
Currently you can't. Why is it important to separate casts and declarations?

**Comment by l4l** [comment]
It's not actually an important feature. Just think it can speed up search for some non-usual cases like this:

```cpp
class A {
    virtual void f() = 0;
};


class B : A {
    f() {}
};

//...
    A a = new A;
    (B)a.f();
//...
```

Btw, stuff like `static/reinterpret/dynamic`-_cast also can be moved to this category

**Comment by egraether** [comment]
Hasn't come up again. Closing now.
