### ISSUE TITLE
Missing MSVCR100.dll throws (wrong) missing Java Exception

### ISSUE THREAD

**Issue by Miguel0888** [CoatiSoftware/Sourcetrail#944]
The message is as follows:
ERROR: Could not load library "C:\Program Files\Java\jre1.8.0_241\bin\server\jvm.dll" because of error "Das angegebene Modul wurde nicht gefunden." (code 126).

After a while of testing I checked it with the "Process Monitor" and found out that the MSVCR100.dll was missing. So I downloaded the C++ Package from Microsoft: 
https://www.microsoft.com/de-de/download/confirmation.aspx?id=26999

It solved the problem but nevertheless the error message was not helpful. Please fix it.

[log_2020-03-23_16-46-19.txt](https://github.com/CoatiSoftware/Sourcetrail/files/4370605/log_2020-03-23_16-46-19.txt)

![Sourcetrail MSVCR100_DLL Error_](https://user-images.githubusercontent.com/40050873/77337870-d00fbb00-6d29-11ea-933b-60ef4a19119d.png)

**Comment by mlangkabel** [comment]
We changed the text of that error message because Sourcetrail not being able to find Java doesn't seem to be the only cause that can lead to this error, as @Miguel0888 demonstrated.
