### ISSUE TITLE
Rename "aggregration" edge to something better understandable

### ISSUE THREAD

**Issue by kobi-ca** [CoatiSoftware/Sourcetrail#962]
2020.1.117 version.
when a type is using another type(function etc...) it is showing as aggregation instead of using.
I'm sure it was different in prev version. any idea?

thanks,
Kobi

**Comment by mlangkabel** [comment]
Hm, I cannot reproduce this issue. Can you please post some example code? or a screenshot?

**Comment by kobi-ca** [comment]
It might be my misunderstanding.
When it says "aggregation 10 edges"
It does not really mean "type A aggregate type B".
I think it means "type A has 10 connections to type B".
right?
I'm looking at the built in example that comes with the installer.
"ArtificialPlayer" does not really aggregate "Field" right?
There are 24 edges as it says "aggregate 24 edges" and it means there are 24 lines (use, call, type use).

If my understanding above is correct, I suggest renaming "aggregation 24 edges" to something else.
maybe ... "multiple relations 24 edges" or some other better name. what do you think?

**Comment by mlangkabel** [comment]
Yes, you understood correctly. "The aggregation edge does not mean that types aggregate but that the edge is an aggregation of multiple different edges.

I think you have a valid point and the name of the edge can be missleading. @egraether: what do you think about renaming this edge?

**Comment by egraether** [comment]
Yes, if renaming makes it more clear, then we should do it (we are not English native speakers after all). Still, we need a new name for this edge type that works as standalone term. Suggestions:
* bundle edge
* collection edge

That's all I can think of. I like **bundle edge**. Any other suggestions?

**Comment by kobi-ca** [comment]
bundle sounds good to me

**Comment by egraether** [comment]
Final decision: `bundled edges`
