### ISSUE TITLE
Is the structure of the sqlite3 project db documented

### ISSUE THREAD

**Issue by schnorea** [CoatiSoftware/Sourcetrail#966]
Is the structure of the project DB (in sqlite) defined anywhere?  

I can see the structure in the sqlite file but other than edges can't figure out the association with the graphical view elements.

Is there a nongraphical tool that provides this same information?  The nice thing of doing this of a graphical tool is that you can easily prune the relivent code out of the wealth of infomation available.

I ask becuase I would like create at reporting functions that would export some of the information presented in the graphical view in a textual format to feed into refactoring workflow for developers.

**Comment by mlangkabel** [comment]
Hi @schnorea, that sounds like an interesting idea. We have heared the request for such tools quite some times, so the demand for such a thing is there!

@LouisStAmour once created a diagram of the DB format (including the functions to store new information to the database as provided by [SourcetrailDB](https://github.com/CoatiSoftware/SourcetrailDB)). You can find it at https://github.com/LouisStAmour/SourcetrailTypescriptIndexer/blob/master/docs/SourcetrailDB%20Schema.pdf
