### ISSUE TITLE
Compiler Flags in Project needs "=" sign

### ISSUE THREAD

**Issue by PhilG57** [CoatiSoftware/Sourcetrail#974]
For the Project to pass flags to the compiler, the definition needs an "=" sign between the variable name and the desired value. 

-D__POCC__ 900   <-- no go with just a space
-D__POCC__=900  <--works great

**Comment by mlangkabel** [comment]
True.

**Comment by egraether** [comment]
Yes, it's not clear to the user. We should mention this in the help message.

**Comment by mlangkabel** [comment]
done with merge of pull request #990
