### ISSUE TITLE
Feature request - Add the solarized color theme

### ISSUE THREAD

**Issue by theidexisted** [CoatiSoftware/Sourcetrail#988]
Any plan to add the solarized color theme? Or there are any documents to show how to adding color theme?

**Comment by mlangkabel** [comment]
Wow, that's a good point you are bringing up here. We designed the color schemes to be easily editable and expendible. But there is not yet any documentation on that. So let me try to clarify it here and if more questions are coming up, we can add to our main documentation.

Each color scheme is defined by an `.xml` file located in the `Sourcetrail/data/color_schemes` folder. To add a new color scheme to Sourcetrail, just copy one of the existing color scheme files, rename it to your likings and start editing. 
To see updates within Sourcetrail for the changes that you did, just open the Sourcetrail preferences and switch to a different color scheme and then back to the one you are editing.

Usually the entries in the `.xml` look like this:
```xml
<snippet>
	<background>white</background>
	<title>
		<text>#909090</text>
		<background>transparent</background>
	</title>
	...
</snippet>
```

But you may also encounter something like this:
```xml
<struct>
	<like>class</like>
</struct>
```
This `like` element is just a shortcut that denotes that in the graph the nodes for `struct`s should be displayed in the same style as nodes for `class`es.

If you want to add the solarized color schemes, we would be happy to accept your pull request :)

**Comment by mlangkabel** [comment]
Added information on how to create new color schemes with merge of pull request #991.

**Comment by prehistoric-penguin** [comment]
Thanks for so quickly response,  I really appreciate your work

**Comment by cr7-ankit** [comment]
Is this issue still open? I am a beginner and new to open Source and looking forward to contributing. It would be a great help if any of you senior can guide me and make me successful in my very first contribution I am willing to do.
Thanks

**Comment by mlangkabel** [comment]
Added with merge of pull request #1195.
