### ISSUE TITLE
How to disable the default (Sourcetrail) global header search path

### ISSUE THREAD

**Issue by Riker-Lin** [CoatiSoftware/Sourcetrail#989]
For global header search paths, there is a default one to point the sourcetrail installation folder. For example, "../Sourcetrail_2019_4_102_64bit/data/cxx/include". Is it possible to disable this?

[Details]
We use the cross-compile GCC toolchain for ARM-64 platform. We follows the guideline (https://www.sourcetrail.com/documentation/#Linux27) to get the GCC search paths and put them into the [Global Include Paths] list box. There is a default (Sourcetrail) global header search path put at the first line and marked as grey. We found that the some header files of Sourcetrail are conflicted with the ones inside our GCC toolchain. It causes the errors (e.g. some symbols are not defined) while  creating the indexes. So, is it possible to disable the default (Sourcetrail) global header search path?

Thank you very much!!

**Comment by egraether** [comment]
Oh, just now realized you are using an old version of Sourcetrail. Please update to the newest one, there was an issue with those headers in that version.

Answer to your question:

No, I think it's not possible to remove the path, but you can just remove or rename the directory it is pointing to. That should have the same effect.

These header files are called the *compiler config*, and as far as I know, you have to use the ones that match your compiler. So if you use GCC ones instead of Sourcetrails internal LLVM/Clang compiler, it won't work.

**Comment by Riker-Lin** [comment]
I download the latest version of Sourcetrail, "2020.1.117". I found that there is no default Sourcetrail ("../Sourcetrail_2019_4_102_64bit/data/cxx/include") path in the [Global Include Paths] list box. I will give it a try, check the original issue about the conflicts of header files is gone or not, and then update here soon.

BTW, thanks for your explanation. I could understand the purpose for those header files. 
But, what does it mean about "you can just remove or rename the directory it is pointing to. That should have the same effect."? Do you mean to rename the folder to 'cxx.backup' as "../Sourcetrail_2019_4_102_64bit/data/cxx.backup/include"? If so, is it okay for the operation of Sourcetrails internal LLVM/Clang compiler?

**Comment by mlangkabel** [comment]
> I found that there is no default Sourcetrail ("../Sourcetrail_2019_4_102_64bit/data/cxx/include") path in the [Global Include Paths] list box.

Cannot reproduce this on Windows. The path is on the filesystem and also displayed in the list box for both, the portable and the installer version of Sourcetrail 2020.1.117.

> Do you mean to rename the folder to 'cxx.backup' as "../Sourcetrail_2019_4_102_64bit/data/cxx.backup/include"? 

Exactly :)

>If so, is it okay for the operation of Sourcetrails internal LLVM/Clang compiler?

It is totally ok for the Clang compiler. If it does not find one of the header search paths or if that path does not have the required contents, Clang will just ignore that path and continue looking into the next header search path in the list.

**Comment by Riker-Lin** [comment]
For the issue of no default Sourcetrail ("../Sourcetrail_2019_4_102_64bit/data/cxx/include") path in the [Global Include Paths] list box, I only see it when I first run Sourcetrail 2020.1.117 and create a new project (first time only).  Then, when I go to edit the project setting or create new projects, the default  Sourcetrail ("../Sourcetrail_2019_4_102_64bit/data/cxx/include") path is existed in the [Global Include Paths] list box with grey color.

BTW, thanks every much for egraether's help. The original issue is fixed by new Sourcetrail 2020.1.117. Thank you!
