### ISSUE TITLE
Sourcetrail.sh:/**/**/Sourcetrail/setup/Linux/Sourcetrail: not found

### ISSUE THREAD

**Issue by haishibei** [CoatiSoftware/Sourcetrail#996]
when I git clone the flies in my computer and  "cd Sourcetrail/setup/Linux", and run "sudo ./Sourcetrail.sh", I encounter the problem"./Sourcetrail.sh: 22: exec: /**/**/Sourcetrail/setup/Linux/Sourcetrail: not found".
then I continue run "sudo ./install.sh", there is another problem "cp: 无法获取'/home/bob/jj/download/Sourcetrail/setup/Linux/setup/share/' 的文件状态(stat): 没有那个文件或目录
Installation complete.
Enter 'sourcetrail' to launch application.
"
When I run ''sourcetrail''   in the terminal , there is one more problem, "/usr/bin/sourcetrail: 22: exec: /opt/sourcetrail/Sourcetrail: not found"
How could I solve the problem???

**Comment by egraether** [comment]
If you just want to download and use Sourcetrail, then download one of the release packages here: https://github.com/CoatiSoftware/Sourcetrail/releases

Only if you want to contribute to Sourcetrail, clone the repository and build it yourself.

**Comment by haishibei** [comment]
ok， thank you!
