### ISSUE TITLE
How to add a file without a suffix

### ISSUE THREAD

**Issue by MicePilot** [CoatiSoftware/Sourcetrail#997]
I only found how to add a file with a suffix name, but for C ++ without a suffix name header file, such as vector, I do not know how to add.

**Comment by egraether** [comment]
What do you mean? It works the same way as your compilers header search paths.

**Comment by mlangkabel** [comment]
I think that the problem may be that it is not clear enough that only source file extensions need to be specified and headers will be indexed on the fly if 
* they are directly or indirectly included from an indexed source file
* they are located within one of the indexed file paths

**Comment by mlangkabel** [comment]
Added this info to help message of source file extension listbox via merge of pull request #1039.
