### ISSUE TITLE
Curiously recurring template pattern isn't indexed

### ISSUE THREAD

**Issue by kubapiszczek** [CoatiSoftware/Sourcetrail#998]
Code as below isn't fully indexed :

// The Curiously Recurring Template Pattern (CRTP)
_template \<class T\>
class Base
{_
    // methods within Base can use template to access members of Derived
_};
class Derived : public Base\<Derived\>
{_
    // ...
_};_

Template class is indexed but all specializations are "non-indexed" so it is not possible to navigate to them from class _Derived_ and from its references.

Tested on: 3fb14b3000dcacd854ed2c451f709b1eb0bc97e3

**Comment by mlangkabel** [comment]
Hm, I cannot reproduce this issue on Windows with Sourcetrail 2020.1.117. This is what it looks like for me:

![image](https://user-images.githubusercontent.com/16242920/81395028-365a6c80-9123-11ea-9825-3f879ef5d0fa.png)
